/**
 * ProjectRepository — generated tests.
 *
 * DO NOT EDIT. This file was generated by RepositoryGenerator.
 */

import { ProjectRepository } from "../ProjectRepository";

describe("ProjectRepository (generated)", () => {
  let repo: ProjectRepository;

  beforeEach(() => {
    repo = new ProjectRepository();
  });

  it("returns null when no events exist", async () => {
    const state = await repo.load("nonexistent-id");
    expect(state).toBeNull();
  });

  it("apply() is deterministic — same events produce same state", async () => {
    const state1 = await repo.load("test-1");
    const state2 = await repo.load("test-1");
    expect(state1).toEqual(state2);
  });

  it("beforeCommand returns true (stub)", async () => {
    const allowed = await repo.beforeCommand("Create", "test-id", "tenant-1");
    expect(allowed).toBe(true);
  });

  it("afterSave is a no-op (stub)", async () => {
    await expect(
      repo.afterSave({ id: "test", version: 0, status: "initial", authority: "ProjectAuthority", events: [] }, []),
    ).resolves.toBeUndefined();
  });

  it("snapshot returns same state (stub)", async () => {
    const state = { id: "test", version: 0, status: "initial", authority: "ProjectAuthority", events: [] as never[] };
    const snapped = await repo.snapshot(state);
    expect(snapped).toEqual(state);
  });
});
