/**
 * CrewAssigned — canonical event type.
 *
 * DO NOT EDIT. Generated by EventGenerator from Canonical IR.
 * Compiler: 1.0.0
 * Constitution: 1.0.0
 * Hash: a837505b78ba1e2efd8d58e5e2fd42105bd84ab868b07e11028332cd96dd66d6
 * Aggregate: Job
 */

import * as crypto from "crypto";
import type { CreateEventInput } from "./createEvent";

export interface CrewAssigned {
  readonly type: "CrewAssigned";
  readonly aggregateId: string;
  readonly authorityId: string;
  readonly tenantId: string;
  readonly replaySequence: number;
  readonly witnessId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly schemaVersion: string;
  readonly timestamp: string;
  readonly contentHash: string;
  readonly payload: Record<string, unknown>;
}

/** Type guard */
export function isCrewAssigned(event: { type: string }): event is CrewAssigned {
  return event.type === "CrewAssigned";
}

/** Type-safe event factory */
export function createCrewAssigned(input: CreateEventInput): CrewAssigned {
  const payload = input.payload ?? {};
  const contentHash = crypto.createHash("sha256").update(JSON.stringify(payload, Object.keys(payload).sort())).digest("hex");
  
  return {
    type: "CrewAssigned",
    aggregateId: input.aggregateId,
    authorityId: input.authorityId,
    tenantId: input.tenantId,
    replaySequence: input.replaySequence,
    witnessId: input.witnessId,
    correlationId: input.correlationId,
    causationId: input.causationId,
    schemaVersion: input.schemaVersion ?? "1.0.0",
    timestamp: input.timestamp ?? new Date().toISOString(),
    contentHash,
    payload,
  };
}

/** Test fixture factory - generates deterministic test events */
export function fixtureCrewAssigned(overrides: Partial<CreateEventInput> = {}): CrewAssigned {
  return createCrewAssigned({
    aggregateId: overrides.aggregateId ?? "test-aggregate-id",
    authorityId: overrides.authorityId ?? "test-authority-id",
    tenantId: overrides.tenantId ?? "test-tenant-id",
    replaySequence: overrides.replaySequence ?? 1,
    witnessId: overrides.witnessId ?? "test-witness-id",
    correlationId: overrides.correlationId ?? "test-correlation-id",
    causationId: overrides.causationId ?? "test-causation-id",
    schemaVersion: overrides.schemaVersion ?? "1.0.0",
    timestamp: overrides.timestamp ?? "2024-01-01T00:00:00.000Z",
    payload: overrides.payload ?? {},
  });
}
