/**
 * EventEnvelope — canonical event structure.
 *
 * DO NOT EDIT. Generated by EventGenerator from Canonical IR.
 * Compiler: 1.0.0
 * Constitution: 1.0.0
 * Hash: 7e8a31c8d61bf9476f1412b4977192529c4c417527e40b40318ae88df65bbe75
 * Every event in the system shares this envelope.
 */

export interface EventEnvelope<T extends string = string, P = unknown> {
  /** Discriminated union key */
  readonly type: T;

  /** Aggregate this event belongs to */
  readonly aggregateId: string;

  /** Authority that emitted this event */
  readonly authorityId: string;

  /** Tenant isolation boundary */
  readonly tenantId: string;

  /** Monotonically increasing replay position */
  readonly replaySequence: number;

  /** Content-hash witness for replay determinism */
  readonly witnessId: string;

  /** Correlation ID for distributed tracing */
  readonly correlationId: string;

  /** Causation ID — the event that caused this one */
  readonly causationId: string;

  /** Schema version for forward compatibility */
  readonly schemaVersion: string;

  /** Lamport timestamp or wall clock (deterministic mode uses replay sequence) */
  readonly timestamp: string;

  /** SHA-256 of the payload for content-addressable storage */
  readonly contentHash: string;

  /** Event-specific payload */
  readonly payload: P;
}

/** All valid event type strings */
export type EventType = "EstimateCreated" | "EstimateAccepted" | "JobCreated" | "CrewAssigned" | "JobCompleted" | "ProjectCreated" | "ProjectCompleted";
