/**
 * ProjectCompleted — canonical event type.
 *
 * DO NOT EDIT. Generated by EventGenerator from Canonical IR.
 * Aggregate: Project
 */

export interface ProjectCompleted {
  readonly type: "ProjectCompleted";
  readonly aggregateId: string;
  readonly authorityId: string;
  readonly tenantId: string;
  readonly replaySequence: number;
  readonly witnessId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly schemaVersion: string;
  readonly timestamp: string;
  readonly contentHash: string;
  readonly payload: Record<string, unknown>;
}

/** Type guard */
export function isProjectCompleted(event: { type: string }): event is ProjectCompleted {
  return event.type === "ProjectCompleted";
}
