import {applyContentMutation,contentSnapshot,decodeContentMutation,isPublicContent,moveContent,type ContentCatalog,type ContentMutation} from '../content-contract';
const catalog=():ContentCatalog=>({projects:Array.from({length:20},(_,i)=>({id:`project-${i+1}`,media:{hero:`photo-${i+1}`},story:{challenge:'Keep the original story'},provenance:{source:'Drive'},order:i}))});
function mutation(data:ContentCatalog,next=moveContent(contentSnapshot(data,'projects'),'project-20',2)):ContentMutation {return {schema:'content.v1',collection:'projects',expectedRevision:data.editorialRevision??0,previous:contentSnapshot(data,'projects'),next};}
it.each([{}, {hidden:false}, {publicationState:'published'}])('keeps legacy/published content visible: %j',item=>expect(isPublicContent(item as never)).toBe(true));
it.each([{hidden:true},{publicationState:'draft'},{archived:true},{status:'archived'}])('blocks unpublished content: %j',item=>expect(isPublicContent(item as never)).toBe(false));
it('moves 20 to 2 in one stable-ID mutation and preserves media/story/provenance',()=>{const data=catalog();const original=structuredClone(data.projects![19]);applyContentMutation(data,mutation(data));expect(data.projects![1]).toEqual({...original,hidden:false,order:1});expect(data.projects!.map(x=>x.id)).toEqual(['project-1','project-20',...Array.from({length:18},(_,i)=>`project-${i+2}`)]);expect(data.editorialRevision).toBe(1);});
it.each([1,20])('moves directly to %i',position=>expect(moveContent(contentSnapshot(catalog(),'projects'),'project-10',position)[position-1].id).toBe('project-10'));
it.each([0,21,1.5,NaN])('rejects invalid positions %s',position=>expect(()=>moveContent(contentSnapshot(catalog(),'projects'),'project-1',position)).toThrow('INVALID_CONTENT_POSITION'));
it('rejects stale revisions without modifying the catalog',()=>{const data=catalog(),change=mutation(data);applyContentMutation(data,change);const confirmed=structuredClone(data);expect(()=>applyContentMutation(data,change)).toThrow('CONTENT_REVISION_CONFLICT');expect(data).toEqual(confirmed);});
it('detects competing metadata/order edits even when revision is unchanged',()=>{const data=catalog(),change=mutation(data);data.projects![0].hidden=true;expect(()=>applyContentMutation(data,change)).toThrow('CONTENT_REVISION_CONFLICT');});
it('hides and restores through two fresh CAS mutations while retaining source data',()=>{const data=catalog(),before=contentSnapshot(data,'projects');applyContentMutation(data,mutation(data,before.map(x=>x.id==='project-1'?{...x,hidden:true}:x)));expect(isPublicContent(data.projects![0])).toBe(false);applyContentMutation(data,mutation(data,before));expect(isPublicContent(data.projects![0])).toBe(true);expect(data.projects![0].provenance).toEqual({source:'Drive'});expect(data.editorialRevision).toBe(2);});
it('does not stage an unchanged order',()=>{const data=catalog();expect(()=>decodeContentMutation(mutation(data,moveContent(contentSnapshot(data,'projects'),'project-1',1)))).toThrow('CONTENT_UNCHANGED');});
it.each(['remove','duplicate','promote'])('rejects unauthorized membership/publication edits: %s',kind=>{const change=mutation(catalog());if(kind==='remove')change.next.pop();if(kind==='duplicate')change.next[1].id=change.next[0].id;if(kind==='promote')change.previous[0].publicationState='draft';expect(()=>decodeContentMutation(change)).toThrow();});
it('normalizes field order and strips unapproved source fields',()=>{const data=catalog(),change=mutation(data);const decoded=decodeContentMutation({...change,next:change.next.map(({id,hidden,order,publicationState})=>({order,id,publicationState,hidden,media:{hero:'drive-raw'}}))});applyContentMutation(data,decoded);expect(data.projects![0].media).toEqual({hero:'photo-1'});});
