jest.mock('@/lib/workbench-session',()=>({workbenchSession:{isAuthenticated:jest.fn()}}));
jest.mock('@/lib/content-authority',()=>({readGitContent:jest.fn(),readContentReceipt:jest.fn(),deployedContent:jest.fn(),listContentReceipts:jest.fn()}));
jest.mock('@/lib/deployment-transaction',()=>({getRedisClient:()=>({eval:mockEval})}));
const mockEval=jest.fn();
import {workbenchSession} from '../workbench-session';
import {readGitContent,readContentReceipt,listContentReceipts,deployedContent} from '../content-authority';
import {contentSnapshot,type ContentMutation} from '../content-contract';
import {POST,GET} from '@/app/api/workbench/content/route';
import {POST as cancel} from '@/app/api/workbench/content/cancel/route';
import {TextError} from '../text-errors';
const id='WBDEP-1791550000000-12345678-1234-1234-1234-123456789abc';
const data={projects:[{id:'project-1',media:{hero:'verified-photo'}}]};
const previous=contentSnapshot(data,'projects');
const mutation:ContentMutation={schema:'content.v1',collection:'projects',expectedRevision:0,previous,next:previous.map(x=>({...x,hidden:true}))};
const request=(body:unknown={transactionId:id,mutation})=>new Request('https://site/api/workbench/content',{method:'POST',body:typeof body==='string'?body:JSON.stringify(body)});
const principal=process.env.HPP_WORKBENCH_PRINCIPAL_ID;
beforeEach(()=>{jest.clearAllMocks();process.env.HPP_WORKBENCH_PRINCIPAL_ID='test-principal';jest.mocked(workbenchSession.isAuthenticated).mockResolvedValue(true);jest.mocked(readGitContent).mockResolvedValue(structuredClone(data));jest.mocked(readContentReceipt).mockResolvedValue({transactionId:id,state:'prepared',mutation,stagingVerified:true} as never);mockEval.mockResolvedValue(['OK']);});
afterAll(()=>{if(principal===undefined)delete process.env.HPP_WORKBENCH_PRINCIPAL_ID;else process.env.HPP_WORKBENCH_PRINCIPAL_ID=principal;});
it('requires authentication for reads, staging and cancellation',async()=>{jest.mocked(workbenchSession.isAuthenticated).mockResolvedValue(false);expect((await POST(request())).status).toBe(401);expect((await GET(new Request('https://site/api/workbench/content?collection=projects'))).status).toBe(401);expect((await cancel(request({transactionId:id}))).status).toBe(401);expect(mockEval).not.toHaveBeenCalled();expect(readGitContent).not.toHaveBeenCalled();});
it.each(['{',{transactionId:'invalid',mutation},{transactionId:id,mutation:{...mutation,next:[]}}])('rejects malformed input without staging',async body=>{expect((await POST(request(body))).status).toBe(400);expect(mockEval).not.toHaveBeenCalled();});
it('does not persist a stale hide or overwrite a competing revision',async()=>{jest.mocked(readGitContent).mockResolvedValue({...data,editorialRevision:1});expect((await POST(request())).status).toBe(409);expect(mockEval).not.toHaveBeenCalled();});
it('atomically binds the immutable change to its principal and collection receipt',async()=>{const response=await POST(request());expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');const result=await response.json();expect(result).toMatchObject({transactionId:id,published:false,stagingVerified:true});const args=mockEval.mock.calls[0];const tx=JSON.parse(args[2][0]);expect(tx).toMatchObject({principalId:'test-principal',files:['projects.v1.json'],contentMutation:mutation});expect(tx.stagingKeys).toHaveLength(1);expect(tx.stagingKeys[0]).toContain(`:${id}:content:projects`);expect(JSON.parse(args[2][1])).toEqual(mutation);});
it('does not report staging as saved without exact readback',async()=>{jest.mocked(readContentReceipt).mockResolvedValue({transactionId:id,state:'prepared',mutation,stagingVerified:false} as never);expect((await POST(request())).status).toBe(409);});
it('retains the confirmed state and redacts dependency secrets on failure',async()=>{mockEval.mockRejectedValue(new Error('secret-token'));const response=await POST(request());expect(response.status).toBe(503);expect(JSON.stringify(await response.json())).not.toContain('secret-token');expect(data.projects[0]).not.toHaveProperty('hidden');});
it('reports immutable receipt collisions as conflicts',async()=>{mockEval.mockRejectedValue(new Error('TEXT_RECEIPT_CONFLICT'));expect((await POST(request())).status).toBe(409);});
it.each([403,404,409])('preserves authority error %i when cancelling',async status=>{jest.mocked(readContentReceipt).mockRejectedValue(new TextError(status,'CONTENT_REJECTED'));expect((await cancel(request({transactionId:id}))).status).toBe(status);expect(mockEval).not.toHaveBeenCalled();});
it('refuses cancellation once the transaction crosses the claim boundary',async()=>{mockEval.mockResolvedValue(['ERR','COMMIT_BOUNDARY']);expect((await cancel(request({transactionId:id}))).status).toBe(409);});
it('serves canonical administrative catalogs without a cacheable response',async()=>{jest.mocked(deployedContent).mockReturnValue(data);jest.mocked(listContentReceipts).mockResolvedValue([]);const response=await GET(new Request('https://site/api/workbench/content?collection=projects'));expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');expect((await response.json()).current).toEqual(data);});
