import {applyContentMutation,contentSnapshot,decodeContentMutation,isPublicContent,moveContent,type ContentCatalog,type ContentMutation} from '../content-contract';
const catalog=():ContentCatalog=>({projects:Array.from({length:20},(_,i)=>({id:`project-${i+1}`,media:{hero:`photo-${i+1}`},story:{challenge:'Keep the original story'},provenance:{source:'Drive'},order:i}))});
function mutation(data:ContentCatalog,next=moveContent(contentSnapshot(data,'projects'),'project-20',2)):ContentMutation {return {schema:'content.v1',collection:'projects',expectedRevision:data.editorialRevision??0,previous:contentSnapshot(data,'projects'),next};}
it.each([{}, {hidden:false}, {publicationState:'published'}])('keeps legacy/published content visible: %j',item=>expect(isPublicContent(item as never)).toBe(true));
it.each([{hidden:true},{publicationState:'draft'},{archived:true},{status:'archived'}])('blocks unpublished content: %j',item=>expect(isPublicContent(item as never)).toBe(false));
it('moves 20 to 2 in one stable-ID mutation and preserves media/story/provenance',()=>{const data=catalog();const original=structuredClone(data.projects![19]);applyContentMutation(data,mutation(data));expect(data.projects![1]).toEqual({...original,hidden:false,order:1});expect(data.projects!.map(x=>x.id)).toEqual(['project-1','project-20',...Array.from({length:18},(_,i)=>`project-${i+2}`)]);expect(data.editorialRevision).toBe(1);});
it.each([1,20])('moves directly to %i',position=>expect(moveContent(contentSnapshot(catalog(),'projects'),'project-10',position)[position-1].id).toBe('project-10'));
it.each([0,21,1.5,NaN])('rejects invalid positions %s',position=>expect(()=>moveContent(contentSnapshot(catalog(),'projects'),'project-1',position)).toThrow('INVALID_CONTENT_POSITION'));
it('rejects stale revisions without modifying the catalog',()=>{const data=catalog(),change=mutation(data);applyContentMutation(data,change);const confirmed=structuredClone(data);expect(()=>applyContentMutation(data,change)).toThrow('CONTENT_REVISION_CONFLICT');expect(data).toEqual(confirmed);});
it('detects competing metadata/order edits even when revision is unchanged',()=>{const data=catalog(),change=mutation(data);data.projects![0].hidden=true;expect(()=>applyContentMutation(data,change)).toThrow('CONTENT_REVISION_CONFLICT');});
it('hides and restores through two fresh CAS mutations while retaining source data',()=>{const data=catalog(),before=contentSnapshot(data,'projects');applyContentMutation(data,mutation(data,before.map(x=>x.id==='project-1'?{...x,hidden:true}:x)));expect(isPublicContent(data.projects![0])).toBe(false);applyContentMutation(data,mutation(data,before));expect(isPublicContent(data.projects![0])).toBe(true);expect(data.projects![0].provenance).toEqual({source:'Drive'});expect(data.editorialRevision).toBe(2);});
it('does not stage an unchanged order',()=>{const data=catalog();expect(()=>decodeContentMutation(mutation(data,moveContent(contentSnapshot(data,'projects'),'project-1',1)))).toThrow('CONTENT_UNCHANGED');});
it.each(['remove','duplicate','promote'])('rejects unauthorized membership/publication edits: %s',kind=>{const change=mutation(catalog());if(kind==='remove')change.next.pop();if(kind==='duplicate')change.next[1].id=change.next[0].id;if(kind==='promote')change.previous[0].publicationState='draft';expect(()=>decodeContentMutation(change)).toThrow();});
it('normalizes field order and strips unapproved source fields',()=>{const data=catalog(),change=mutation(data);const decoded=decodeContentMutation({...change,next:change.next.map(({id,hidden,order,publicationState})=>({order,id,publicationState,hidden,media:{hero:'drive-raw'}}))});applyContentMutation(data,decoded);expect(data.projects![0].media).toEqual({hero:'photo-1'});});
function copyMutation(data:ContentCatalog,field='story.challenge',previousValue='Keep the original story',value='The exact revised challenge.'):ContentMutation {
  const rows=contentSnapshot(data,'projects');return {schema:'content.v1',collection:'projects',expectedRevision:data.editorialRevision??0,previous:rows,next:rows,copy:[{id:'project-1',field,previousValue,value}]};
}
it('edits canonical story through the existing revision while retaining media, identity, and provenance',()=>{
  const data=catalog(),original=structuredClone(data.projects![0]);applyContentMutation(data,copyMutation(data));
  expect(data.projects![0]).toEqual({...original,hidden:false,story:{challenge:'The exact revised challenge.'}});expect(data.editorialRevision).toBe(1);
});
it('detects copy conflicts even if editorial revision and visibility stayed unchanged',()=>{
  const data=catalog(),change=copyMutation(data);data.projects![0].story={challenge:'A concurrent change'};const confirmed=structuredClone(data);
  expect(()=>applyContentMutation(data,change)).toThrow('CONTENT_COPY_REVISION_CONFLICT');expect(data).toEqual(confirmed);
});
it.each(['id','slug','service','media.hero','provenance.source','publicationState','story.__proto__.challenge'])('rejects copy promotion through locked field %s',field=>expect(()=>decodeContentMutation(copyMutation(catalog(),field))).toThrow('INVALID_CONTENT_COPY'));
it.each(['','   ','<script>bad</script>','line\nbreak'])('rejects invalid content copy %j',value=>expect(()=>decodeContentMutation(copyMutation(catalog(),'story.challenge','Keep the original story',value))).toThrow('INVALID_CONTENT_COPY'));
it('rejects creating an absent canonical field and leaves the entire catalog intact',()=>{const data=catalog(),confirmed=structuredClone(data);expect(()=>applyContentMutation(data,copyMutation(data,'title','','New title'))).toThrow('CONTENT_COPY_REVISION_CONFLICT');expect(data).toEqual(confirmed);});
it('preserves exact spaces and punctuation while binding and normalizing the immutable copy receipt',()=>{const change=copyMutation(catalog(),'story.challenge','Keep the original story',' Exact punctuation — and spacing. ');expect(decodeContentMutation({...change,copy:change.copy!.map(row=>({...row,mediaId:'drive-raw'}))})).toEqual(change);});
it('edits an existing array element without changing membership or sibling story fields',()=>{const data=catalog();data.projects![0].story={challenge:'Keep the original story',specialFeatures:['Cedar joints','Original finish']};applyContentMutation(data,copyMutation(data,'story.specialFeatures.0','Cedar joints','Hand-cut cedar joints'));expect(data.projects![0].story).toEqual({challenge:'Keep the original story',specialFeatures:['Hand-cut cedar joints','Original finish']});});
it('does not partially apply a batch when its last canonical copy value conflicts',()=>{const data=catalog(),change=copyMutation(data);change.copy!.push({id:'project-2',field:'story.challenge',previousValue:'Wrong baseline',value:'Another change'});const confirmed=structuredClone(data);expect(()=>applyContentMutation(data,change)).toThrow('CONTENT_COPY_REVISION_CONFLICT');expect(data).toEqual(confirmed);});
