/**
 * Calendar — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface CalendarProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const calendarProviderMetadata: CalendarProviderMetadata = {
  id: "calendar",
  name: "Calendar",
  capabilities: ["Schedule","Query","Update"],
  priority: "secondary",
  region: "global",
  configSchema: {},
};

/** Type guard */
export function isCalendarProviderMetadata(metadata: { id: string }): metadata is CalendarProviderMetadata {
  return metadata.id === "calendar";
}
