/**
 * CRM — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface CRMProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const cRMProviderMetadata: CRMProviderMetadata = {
  id: "cRM",
  name: "CRM",
  capabilities: ["UpsertContact","QueryContact"],
  priority: "secondary",
  region: "global",
  configSchema: {},
};

/** Type guard */
export function isCRMProviderMetadata(metadata: { id: string }): metadata is CRMProviderMetadata {
  return metadata.id === "cRM";
}
