/**
 * Messaging — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface MessagingProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const messagingProviderMetadata: MessagingProviderMetadata = {
  id: "messaging",
  name: "Messaging",
  capabilities: ["Send","Receive"],
  priority: "secondary",
  region: "global",
  configSchema: {},
};

/** Type guard */
export function isMessagingProviderMetadata(metadata: { id: string }): metadata is MessagingProviderMetadata {
  return metadata.id === "messaging";
}
