/**
 * Payments — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface PaymentsProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const paymentsProviderMetadata: PaymentsProviderMetadata = {
  id: "payments",
  name: "Payments",
  capabilities: ["Charge","Refund","Query"],
  priority: "secondary",
  region: "global",
  configSchema: {},
};

/** Type guard */
export function isPaymentsProviderMetadata(metadata: { id: string }): metadata is PaymentsProviderMetadata {
  return metadata.id === "payments";
}
