/**
 * ProviderRegistry — canonical provider registry metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects from this metadata.
 */

import { Calendar, Payments, CRM, Messaging, Storage, Vision, Scheduling } from "./index";

export interface ProviderRegistry {
  calendar: CalendarProviderMetadata;
  payments: PaymentsProviderMetadata;
  cRM: CRMProviderMetadata;
  messaging: MessagingProviderMetadata;
  storage: StorageProviderMetadata;
  vision: VisionProviderMetadata;
  scheduling: SchedulingProviderMetadata;
}

export const providerRegistry: ProviderRegistry = {
  calendar: calendarProviderMetadata,
  payments: paymentsProviderMetadata,
  cRM: cRMProviderMetadata,
  messaging: messagingProviderMetadata,
  storage: storageProviderMetadata,
  vision: visionProviderMetadata,
  scheduling: schedulingProviderMetadata,
};

export type ProviderId = keyof ProviderRegistry;
