/**
 * Scheduling — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface SchedulingProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const schedulingProviderMetadata: SchedulingProviderMetadata = {
  id: "scheduling",
  name: "Scheduling",
  capabilities: ["Plan","Assign"],
  priority: "secondary",
  region: "global",
  configSchema: {},
};

/** Type guard */
export function isSchedulingProviderMetadata(metadata: { id: string }): metadata is SchedulingProviderMetadata {
  return metadata.id === "scheduling";
}
