/**
 * Storage — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface StorageProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const storageProviderMetadata: StorageProviderMetadata = {
  id: "storage",
  name: "Storage",
  capabilities: ["Acquire","Mirror","Canonicalize","Emit"],
  priority: "secondary",
  region: "global",
  configSchema: {},
};

/** Type guard */
export function isStorageProviderMetadata(metadata: { id: string }): metadata is StorageProviderMetadata {
  return metadata.id === "storage";
}
