/**
 * Vision — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface VisionProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const visionProviderMetadata: VisionProviderMetadata = {
  id: "vision",
  name: "Vision",
  capabilities: ["Detect","Classify"],
  priority: "secondary",
  region: "global",
  configSchema: {},
};

/** Type guard */
export function isVisionProviderMetadata(metadata: { id: string }): metadata is VisionProviderMetadata {
  return metadata.id === "vision";
}
