/**
 * Calendar — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface CalendarCapability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const calendarCapability: CalendarCapability = {
  id: "calendar",
  name: "Calendar",
  description: "",
  contract: ["Schedule","Query","Update"],
};

/** Type guard */
export function isCalendarCapability(capability: { id: string }): capability is CalendarCapability {
  return capability.id === "calendar";
}
