/**
 * CapabilityRegistry — canonical capability registry.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 */

import { Calendar, Payments, CRM, Messaging, Storage, Vision, Scheduling } from "./index";

export interface CapabilityRegistry {
  calendar: CalendarCapability;
  payments: PaymentsCapability;
  cRM: CRMCapability;
  messaging: MessagingCapability;
  storage: StorageCapability;
  vision: VisionCapability;
  scheduling: SchedulingCapability;
}

export const capabilityRegistry: CapabilityRegistry = {
  calendar: calendarCapability,
  payments: paymentsCapability,
  cRM: cRMCapability,
  messaging: messagingCapability,
  storage: storageCapability,
  vision: visionCapability,
  scheduling: schedulingCapability,
};

export type CapabilityId = keyof CapabilityRegistry;
