/**
 * CRM — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface CRMCapability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const cRMCapability: CRMCapability = {
  id: "cRM",
  name: "CRM",
  description: "",
  contract: ["UpsertContact","QueryContact"],
};

/** Type guard */
export function isCRMCapability(capability: { id: string }): capability is CRMCapability {
  return capability.id === "cRM";
}
