/**
 * Messaging — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface MessagingCapability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const messagingCapability: MessagingCapability = {
  id: "messaging",
  name: "Messaging",
  description: "",
  contract: ["Send","Receive"],
};

/** Type guard */
export function isMessagingCapability(capability: { id: string }): capability is MessagingCapability {
  return capability.id === "messaging";
}
