/**
 * Payments — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface PaymentsCapability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const paymentsCapability: PaymentsCapability = {
  id: "payments",
  name: "Payments",
  description: "",
  contract: ["Charge","Refund","Query"],
};

/** Type guard */
export function isPaymentsCapability(capability: { id: string }): capability is PaymentsCapability {
  return capability.id === "payments";
}
