/**
 * Scheduling — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface SchedulingCapability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const schedulingCapability: SchedulingCapability = {
  id: "scheduling",
  name: "Scheduling",
  description: "",
  contract: ["Plan","Assign"],
};

/** Type guard */
export function isSchedulingCapability(capability: { id: string }): capability is SchedulingCapability {
  return capability.id === "scheduling";
}
