/**
 * Storage — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface StorageCapability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const storageCapability: StorageCapability = {
  id: "storage",
  name: "Storage",
  description: "",
  contract: ["Acquire","Mirror","Canonicalize","Emit"],
};

/** Type guard */
export function isStorageCapability(capability: { id: string }): capability is StorageCapability {
  return capability.id === "storage";
}
