/**
 * Vision — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface VisionCapability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const visionCapability: VisionCapability = {
  id: "vision",
  name: "Vision",
  description: "",
  contract: ["Detect","Classify"],
};

/** Type guard */
export function isVisionCapability(capability: { id: string }): capability is VisionCapability {
  return capability.id === "vision";
}
