/**
 * PDFProjection — read model projection.
 *
 * DO NOT EDIT. Generated by ProjectionGenerator from Canonical IR.
 * Business queries are handwritten. This file provides projection plumbing.
 *
 * Events subscribed: none
 */

export interface PDFReadModel {
  readonly id: string;
  readonly tenantId: string;
  readonly version: number;
  readonly updatedAt: string;
  readonly data: Record<string, unknown>;
}

export interface ProjectionEvent {
  readonly type: string;
  readonly aggregateId: string;
  readonly tenantId: string;
  readonly timestamp: string;
  readonly payload: Record<string, unknown>;
}

/**
 * PDFProjection — subscribes to events and builds a read model.
 */
export class PDFProjection {
  /** Projection name (unique identifier) */
  readonly name = "PDF";

  /** Version of this projection schema */
  readonly version = 1;

  /** Events this projection subscribes to */
  readonly subscribesTo = [] as const;

  /** Indexes for efficient queries */
  readonly indexes = ["id", "tenantId", "version"] as const;

  /** Internal state */
  private readonly readModels = new Map<string, PDFReadModel>();

  /**
   * Handle a single event. Pure function: state + event → new state.
   */
  handle(model: PDFReadModel | null, event: ProjectionEvent): PDFReadModel {
    const previous = model ?? {
      id: event.aggregateId,
      tenantId: event.tenantId,
      version: 0,
      updatedAt: event.timestamp,
      data: {},
    };

    return {
      ...previous,
      version: previous.version + 1,
      updatedAt: event.timestamp,
      data: {
        ...previous.data,
        ...event.payload,
      },
    };
  }

  /**
   * Project an event into the read model store.
   */
  async project(event: ProjectionEvent): Promise<void> {
    const existing = this.readModels.get(event.aggregateId) ?? null;
    const updated = this.handle(existing, event);
    this.readModels.set(event.aggregateId, updated);
  }

  /**
   * Query a read model by ID.
   * Business-specific queries should be added as methods on this class.
   */
  async query(id: string): Promise<PDFReadModel | null> {
    return this.readModels.get(id) ?? null;
  }

  /**
   * Query all read models for a tenant.
   */
  async queryByTenant(tenantId: string): Promise<readonly PDFReadModel[]> {
    return Array.from(this.readModels.values()).filter((m) => m.tenantId === tenantId);
  }

  /**
   * Tenant isolation boundary.
   * Ensures no cross-tenant data leakage.
   */
  async queryIsolated(id: string, tenantId: string): Promise<PDFReadModel | null> {
    const model = this.readModels.get(id);
    if (!model || model.tenantId !== tenantId) return null;
    return model;
  }

  /**
   * Rebuild the projection from an event stream.
   * Used for schema migrations and replay-based rebuilds.
   */
  async rebuild(events: readonly ProjectionEvent[]): Promise<void> {
    this.readModels.clear();
    for (const event of events) {
      await this.project(event);
    }
  }

  /**
   * Take a snapshot of the projection state.
   */
  snapshot(): Record<string, PDFReadModel> {
    return Object.fromEntries(this.readModels);
  }

  /**
   * Restore from a snapshot.
   */
  restoreSnapshot(data: Record<string, PDFReadModel>): void {
    this.readModels.clear();
    for (const [key, value] of Object.entries(data)) {
      this.readModels.set(key, value);
    }
  }
}
