/**
 * ProjectionRegistry — central registry of all projections.
 *
 * DO NOT EDIT. Generated by ProjectionGenerator from Canonical IR.
 */

import { CustomerProjection } from "./CustomerProjection";
import { CrewProjection } from "./CrewProjection";
import { VendorProjection } from "./VendorProjection";
import { EstimateProjection } from "./EstimateProjection";
import { JobProjection } from "./JobProjection";
import { ProjectProjection } from "./ProjectProjection";
import { PhotoProjection } from "./PhotoProjection";
import { VideoProjection } from "./VideoProjection";
import { VoiceProjection } from "./VoiceProjection";
import { PDFProjection } from "./PDFProjection";

export interface Projection {
  readonly name: string;
  readonly version: number;
  readonly subscribesTo: readonly string[];
  readonly indexes: readonly string[];
  project(event: { type: string; aggregateId: string; tenantId: string; timestamp: string; payload: Record<string, unknown> }): Promise<void>;
  rebuild(events: { type: string; aggregateId: string; tenantId: string; timestamp: string; payload: Record<string, unknown> }[]): Promise<void>;
}

/** All registered projections */
export const PROJECTIONS: Record<string, Projection> = {
  customer: new CustomerProjection(),
  crew: new CrewProjection(),
  vendor: new VendorProjection(),
  estimate: new EstimateProjection(),
  job: new JobProjection(),
  project: new ProjectProjection(),
  photo: new PhotoProjection(),
  video: new VideoProjection(),
  voice: new VoiceProjection(),
  pDF: new PDFProjection(),
};

/** Get a projection by name */
export function getProjection(name: string): Projection | undefined {
  return PROJECTIONS[name];
}

/** Get all projection names */
export function getProjectionNames(): string[] {
  return Object.keys(PROJECTIONS);
}

/** Route an event to all subscribed projections */
export async function routeEvent(event: { type: string; [key: string]: unknown }): Promise<void> {
  const eventType = (event as { type: string }).type;
  for (const projection of Object.values(PROJECTIONS)) {
    if (projection.subscribesTo.includes(eventType)) {
      await projection.project(event as { type: string; aggregateId: string; tenantId: string; timestamp: string; payload: Record<string, unknown> });
    }
  }
}
