/**
 * Gallery Authority - Photo Database
 * 
 * gallery.json is the photo presentation database.
 * Generated by image-pipeline.mjs from local intake or Drive sync.
 * 
 * Architecture: Google Drive → Photo Pipeline → Gallery Authority → Website Presentation
 * 
 * Canonical Identity: Drive File ID (driveId), not filename
 * Renaming a file in Drive should not break references.
 */

export interface GalleryImageVariants {
  width: number;
  format: "avif" | "webp";
  src: string;
}

export interface GalleryImageProvenance {
  sourceFile: string; // Original filename from source
  importedAt: string; // ISO date string
  pipelineVersion: string;
  driveId?: string; // Google Drive File ID (canonical identity)
  driveFolder?: string; // Drive folder path for validation
  driveModifiedAt?: string; // Drive file modification time
}

export interface GalleryImage {
  uuid: string;
  contentHash: string;
  id: string; // project/image-name format
  title: string;
  project: string;
  category: string;
  county: string;
  featured: boolean;
  before: boolean;
  after: boolean;
  hero: boolean;
  alt: string;
  width: number;
  height: number;
  focal: {
    x: number;
    y: number;
  };
  original: string;
  src: string;
  thumbnail: string;
  blurDataURL: string;
  variants: GalleryImageVariants[];
  provenance: GalleryImageProvenance;
}

export interface GalleryProjectImages {
  hero: GalleryImage | null;
  cover: GalleryImage | null;
  thumbnail: GalleryImage | null;
  homeowner: GalleryImage | null;
  before: GalleryImage[];
  after: GalleryImage[];
  details: GalleryImage[];
}

export interface GalleryProject {
  slug: string;
  uuid: string;
  title: string;
  category: string;
  county: string;
  images: GalleryProjectImages;
  galleryOrder: string[];
}

export interface Gallery {
  projects: GalleryProject[];
}
