import catalog from '@/config/strings.v1.json';
import { decodeTextCatalog, type TextKey } from './text-contract';
export const BLOG_COPY_RECORDS = [
  {
    "id": 1,
    "slug": "spring-maintenance-checklist",
    "date": "2024-03-15",
    "titleKey": "blog.article.spring-maintenance-checklist.title",
    "excerptKey": "blog.article.spring-maintenance-checklist.excerpt",
    "categoryKey": "blog.article.spring-maintenance-checklist.category",
    "body": [
      null,
      "blog.article.spring-maintenance-checklist.line.1",
      null,
      "blog.article.spring-maintenance-checklist.line.3",
      null,
      "blog.article.spring-maintenance-checklist.line.5",
      null,
      "blog.article.spring-maintenance-checklist.line.7",
      "blog.article.spring-maintenance-checklist.line.8",
      "blog.article.spring-maintenance-checklist.line.9",
      "blog.article.spring-maintenance-checklist.line.10",
      null,
      "blog.article.spring-maintenance-checklist.line.12",
      null,
      "blog.article.spring-maintenance-checklist.line.14",
      "blog.article.spring-maintenance-checklist.line.15",
      "blog.article.spring-maintenance-checklist.line.16",
      "blog.article.spring-maintenance-checklist.line.17",
      null,
      "blog.article.spring-maintenance-checklist.line.19",
      null,
      "blog.article.spring-maintenance-checklist.line.21",
      "blog.article.spring-maintenance-checklist.line.22",
      "blog.article.spring-maintenance-checklist.line.23",
      null,
      "blog.article.spring-maintenance-checklist.line.25",
      null,
      "blog.article.spring-maintenance-checklist.line.27",
      "blog.article.spring-maintenance-checklist.line.28",
      "blog.article.spring-maintenance-checklist.line.29",
      "blog.article.spring-maintenance-checklist.line.30",
      "blog.article.spring-maintenance-checklist.line.31",
      null,
      "blog.article.spring-maintenance-checklist.line.33",
      null
    ]
  },
  {
    "id": 2,
    "slug": "deck-maintenance-guide",
    "date": "2024-02-20",
    "titleKey": "blog.article.deck-maintenance-guide.title",
    "excerptKey": "blog.article.deck-maintenance-guide.excerpt",
    "categoryKey": "blog.article.deck-maintenance-guide.category",
    "body": [
      null,
      "blog.article.deck-maintenance-guide.line.1",
      null,
      "blog.article.deck-maintenance-guide.line.3",
      null,
      "blog.article.deck-maintenance-guide.line.5",
      null,
      "blog.article.deck-maintenance-guide.line.7",
      null,
      "blog.article.deck-maintenance-guide.line.9",
      "blog.article.deck-maintenance-guide.line.10",
      "blog.article.deck-maintenance-guide.line.11",
      "blog.article.deck-maintenance-guide.line.12",
      null,
      "blog.article.deck-maintenance-guide.line.14",
      null,
      "blog.article.deck-maintenance-guide.line.16",
      "blog.article.deck-maintenance-guide.line.17",
      "blog.article.deck-maintenance-guide.line.18",
      "blog.article.deck-maintenance-guide.line.19",
      null,
      "blog.article.deck-maintenance-guide.line.21",
      null,
      "blog.article.deck-maintenance-guide.line.23",
      "blog.article.deck-maintenance-guide.line.24",
      "blog.article.deck-maintenance-guide.line.25",
      "blog.article.deck-maintenance-guide.line.26",
      null,
      "blog.article.deck-maintenance-guide.line.28",
      null,
      "blog.article.deck-maintenance-guide.line.30",
      "blog.article.deck-maintenance-guide.line.31",
      "blog.article.deck-maintenance-guide.line.32",
      null,
      "blog.article.deck-maintenance-guide.line.34",
      null
    ]
  },
  {
    "id": 3,
    "slug": "kitchen-remodeling-trends",
    "date": "2024-01-10",
    "titleKey": "blog.article.kitchen-remodeling-trends.title",
    "excerptKey": "blog.article.kitchen-remodeling-trends.excerpt",
    "categoryKey": "blog.article.kitchen-remodeling-trends.category",
    "body": [
      null,
      "blog.article.kitchen-remodeling-trends.line.1",
      null,
      "blog.article.kitchen-remodeling-trends.line.3",
      null,
      "blog.article.kitchen-remodeling-trends.line.5",
      null,
      "blog.article.kitchen-remodeling-trends.line.7",
      "blog.article.kitchen-remodeling-trends.line.8",
      "blog.article.kitchen-remodeling-trends.line.9",
      "blog.article.kitchen-remodeling-trends.line.10",
      null,
      "blog.article.kitchen-remodeling-trends.line.12",
      null,
      "blog.article.kitchen-remodeling-trends.line.14",
      "blog.article.kitchen-remodeling-trends.line.15",
      "blog.article.kitchen-remodeling-trends.line.16",
      "blog.article.kitchen-remodeling-trends.line.17",
      null,
      "blog.article.kitchen-remodeling-trends.line.19",
      null,
      "blog.article.kitchen-remodeling-trends.line.21",
      "blog.article.kitchen-remodeling-trends.line.22",
      "blog.article.kitchen-remodeling-trends.line.23",
      "blog.article.kitchen-remodeling-trends.line.24",
      null,
      "blog.article.kitchen-remodeling-trends.line.26",
      null,
      "blog.article.kitchen-remodeling-trends.line.28",
      "blog.article.kitchen-remodeling-trends.line.29",
      "blog.article.kitchen-remodeling-trends.line.30",
      "blog.article.kitchen-remodeling-trends.line.31",
      null,
      "blog.article.kitchen-remodeling-trends.line.33",
      null
    ]
  }
] as const;
export function getBlogCopy(slug: string) {
 const record=BLOG_COPY_RECORDS.find(post=>post.slug===slug);
 if(!record)return null;const text=decodeTextCatalog(catalog);
 return {...record,title:text.fields[record.titleKey as TextKey].value,category:text.fields[record.categoryKey as TextKey].value,excerpt:text.fields[record.excerptKey as TextKey].value,content:record.body.map(key=>key?text.fields[key as TextKey].value:'').join('\n')};
}
