/**
 * Constitutional Brand Adapter
 * 
 * Constitutional Rule: Frontend performs no media selection, ranking, or sorting.
 * All media decisions are projections generated by Projection Generator.
 * 
 * Brand assets (hero, owner portrait) should come from projection artifacts.
 * 
 * Reference: CONSTITUTIONAL_GALLERY_RECONCILIATION_REPORT.md
 * - Section: Projection Artifacts
 * - Section: Projection Invariants
 */

import type { BrandManifest, BrandHero, BrandOwnerPortrait } from "@/types/brand";
import { loadAuthority, clearAuthorityCache } from "./authority-loader";
import { getHomepageHeroMedia } from "./media";
import { isWorkbenchPreviewMode } from "./media";

export function loadBrandManifest(): BrandManifest {
  const previewMode = isWorkbenchPreviewMode();
  
  if (previewMode) {
    // Use main authority for Workbench preview
    try {
      const { loadMainBrandAuthority } = require('./main-authority-loader');
      return loadMainBrandAuthority();
    } catch (error) {
      console.error('Failed to load main brand authority:', error);
      return {
        version: "1.0.0",
        generatedAt: new Date().toISOString(),
        homepageHero: {
          id: "fallback-hero",
          mediaId: null,
          alt: "Fallback hero",
          fallback: { gradient: true, overlay: true },
        },
        ownerPortrait: {
          id: "fallback-owner",
          mediaId: null,
          alt: "Fallback owner portrait",
          names: [],
        },
        logo: {
          id: "fallback-logo",
          mediaId: null,
          alt: "Fallback logo",
        },
        team: [],
        office: {
          id: "fallback-office",
          mediaId: null,
          alt: "Fallback office",
        },
        marketingAssets: [],
      };
    }
  }
  
  return loadAuthority<BrandManifest>({
    path: "@/config/brand.v1.json",
    fallback: {
      version: "1.0.0",
      generatedAt: new Date().toISOString(),
      homepageHero: {
        id: "fallback-hero",
        mediaId: null,
        alt: "Fallback hero",
        fallback: { gradient: true, overlay: true },
      },
      ownerPortrait: {
        id: "fallback-owner",
        mediaId: null,
        alt: "Fallback owner portrait",
        names: [],
      },
      logo: {
        id: "fallback-logo",
        mediaId: null,
        alt: "Fallback logo",
      },
      team: [],
      office: {
        id: "fallback-office",
        mediaId: null,
        alt: "Fallback office",
      },
      marketingAssets: [],
    },
    name: "Brand",
  });
}

/**
 * Get homepage hero image
 * Constitutional: Reads from heroProjection.json, no selection logic, no fallback
 * 
 * If projection has no hero, this throws (constitutional: build should fail)
 */
export function getHomepageHero(): BrandHero {
  const heroMedia = getHomepageHeroMedia();
  
  if (!heroMedia) {
    throw new Error("Constitutional violation: Homepage hero projection missing or invalid. Build should fail.");
  }
  
  return {
    id: "projection-hero",
    mediaId: heroMedia.id,
    alt: heroMedia.alt || "Homepage hero",
    fallback: { gradient: true, overlay: true },
  };
}

/**
 * Get owner portrait
 * Returns owner portrait or null if not set
 */
export function getOwnerPortrait(): BrandOwnerPortrait | null {
  const manifest = loadBrandManifest();
  return manifest.ownerPortrait;
}

/**
 * Get logo
 */
export function getLogo() {
  const manifest = loadBrandManifest();
  return manifest.logo;
}

/**
 * Get team photos
 */
export function getTeamPhotos() {
  const manifest = loadBrandManifest();
  return manifest.team;
}

/**
 * Get office photo
 */
export function getOfficePhoto() {
  const manifest = loadBrandManifest();
  return manifest.office;
}

/**
 * Get marketing assets
 */
export function getMarketingAssets() {
  const manifest = loadBrandManifest();
  return manifest.marketingAssets;
}

/**
 * Clear brand cache (useful for testing or hot reload)
 */
export function clearBrandCache(): void {
  clearAuthorityCache("@/config/brand.v1.json");
}
