/**
 * Constitutional Media Adapter
 * 
 * Constitutional Rule: Frontend performs no media selection, ranking, or sorting.
 * All media decisions are projections generated by Projection Generator.
 * 
 * This adapter reads from projection artifacts via ProjectionLoader, never performs selection logic.
 * 
 * Reference: CONSTITUTIONAL_GALLERY_RECONCILIATION_REPORT.md
 * - Section: Projection Artifacts
 * - Section: Projection Invariants
 * 
 * Architecture:
 *   Canonical Graph → Projection Generator → Projection Artifacts → ProjectionLoader → Adapter → Component
 * 
 * Never:
 *   Component → Selection Logic → Media
 *   Runtime → Sorting/Ranking → Media
 *   Adapter → Filesystem (IO is handled by ProjectionLoader)
 */

import type { Media, MediaManifest } from "@/types/media";
import { loadAuthority, clearAuthorityCache } from "./authority-loader";
import { loadServiceProjection, loadHeroProjection, loadGalleryProjection } from "./projection-loader";

// Load media manifest using shared AuthorityLoader
export function loadMediaManifest(): MediaManifest {
  return loadAuthority<MediaManifest>({
    path: "@/config/media.v1.json",
    fallback: { version: "1.0.0", generatedAt: new Date().toISOString(), media: [] },
    name: "Media"
  });
}

/**
 * Get the full media manifest (for Authority Editor)
 */
export function getMediaManifest(): MediaManifest {
  return loadMediaManifest();
}

/**
 * Get media by ID from media.v1.json
 * Constitutional: This is a lookup, not selection
 */
export function getMediaById(id: string): Media | null {
  const manifest = loadMediaManifest();
  return manifest.media.find((m: Media) => m.id === id) || null;
}

/**
 * Clear media cache (useful for testing or hot reload)
 */
export function clearMediaCache(): void {
  clearAuthorityCache("@/config/media.v1.json");
}

/**
 * CONSTITUTIONAL VIOLATION NOTICE
 * 
 * The following functions have been removed as they violate constitutional rules:
 * - getProjectMedia (sorting logic)
 * - getProjectHero (selection logic)
 * - getProjectThumbnail (selection logic)
 * - getProjectBeforeAfter (selection logic)
 * - getProjectMediaByRole (selection logic)
 * - getFeaturedServiceMedia (ranking and selection logic)
 * 
 * These functions performed media selection, ranking, and sorting in the frontend.
 * Per constitutional architecture, all media decisions must be projections generated
 * by the Projection Generator and consumed via projection artifacts.
 * 
 * Components should read from:
 * - galleryProjection.json (for gallery media)
 * - heroProjection.json (for hero media)
 * - serviceProjection.json (for service preview media)
 */

/**
 * COMPATIBILITY SHIM FOR AUG 3 UI
 * 
 * getFeaturedServiceMedia is provided for compatibility with Aug 3 UI components.
 * This function delegates to the current projection-based system (getServicePreviewMedia).
 * 
 * Aug 3 UI components were written before the constitutional projection system.
 * This shim maintains the Aug 3 interface while using the current architecture.
 */
export function getFeaturedServiceMedia(serviceSlug: string): Media | null {
  return getServicePreviewMedia(serviceSlug);
}

/**
 * PROJECTION-BASED MEDIA ADAPTER
 * 
 * These functions read from projection artifacts via ProjectionLoader.
 * No selection, ranking, or sorting logic in the frontend.
 * No filesystem access in adapters (handled by ProjectionLoader).
 */

/**
 * Get service preview media from projection
 * Constitutional: Reads from projection artifact, no selection logic, no filesystem access
 */
export function getServicePreviewMedia(serviceSlug: string): Media | null {
  const projection = loadServiceProjection();
  const service = projection.services.find((s: any) => s.serviceName === serviceSlug);
  
  if (!service) return null;
  
  // Look up media by filename from media manifest
  const manifest = loadMediaManifest();
  return manifest.media.find((m: Media) => m.filename === service.serviceRepresentative) || null;
}

/**
 * Get homepage hero media from projection
 * Constitutional: Reads from projection artifact, no selection logic, no filesystem access
 */
export function getHomepageHeroMedia(): Media | null {
  const projection = loadHeroProjection();
  
  // Look up media by filename from media manifest
  const manifest = loadMediaManifest();
  return manifest.media.find((m: Media) => m.filename === projection.hero.filename) || null;
}

/**
 * Get gallery media for a project from projection
 * Constitutional: Reads from projection artifact, no selection logic, no filesystem access
 */
export function getGalleryMediaForProject(projectId: string): { representative: Media | null; supporting: Media[] } {
  const projection = loadGalleryProjection();
  const project = projection.projects.find((p: any) => p.projectId === projectId);
  
  if (!project) return { representative: null, supporting: [] };
  
  const manifest = loadMediaManifest();
  const representative = manifest.media.find((m: Media) => m.filename === project.galleryRepresentative) || null;
  const supporting = project.supportingGalleryEvidence
    .map((filename: string) => manifest.media.find((m: Media) => m.filename === filename))
    .filter((m: Media | undefined) => m !== undefined);
  
  return { representative, supporting };
}
