/**
 * AuthorityRegistry — maps authority name → ownership, events, constraints.
 *
 * DO NOT EDIT. Generated by AuthorityGenerator from Canonical IR.
 * No handwritten authority registration.
 */

export interface AuthorityEntry {
  readonly owns: readonly string[];
  readonly emitsFor: readonly string[];
  readonly constraints: readonly string[];
  readonly deterministic: boolean;
}

export const AUTHORITY_REGISTRY: Record<string, AuthorityEntry> = {
  "IdentityAuthority": {
    owns: ["Customer", "Crew", "Vendor"],
    emitsFor: [],
    constraints: [],
    deterministic: true,
  },
  "MissionAuthority": {
    owns: ["Estimate", "Job", "Project"],
    emitsFor: [],
    constraints: [],
    deterministic: true,
  },
  "EvidenceAuthority": {
    owns: ["Photo", "Video", "Voice", "PDF"],
    emitsFor: [],
    constraints: [],
    deterministic: true,
  },
  "ObservationAuthority": {
    owns: ["RoofDamage", "WaterLeak", "BrokenWindow"],
    emitsFor: ["Claim"],
    constraints: [],
    deterministic: true,
  },
  "FactAuthority": {
    owns: [],
    emitsFor: [],
    constraints: [],
    deterministic: true,
  }
};

/**
 * Get all authority names.
 */
export function getAuthorityNames(): string[] {
  return Object.keys(AUTHORITY_REGISTRY);
}

/**
 * Get an authority entry by name.
 */
export function getAuthority(name: string): AuthorityEntry | undefined {
  return AUTHORITY_REGISTRY[name];
}
