/**
 * Capability Registry Generator — IR → Canonical capability registry.
 *
 * Generates capability definitions and registry from IR.
 * Capabilities are abstract; providers implement capabilities.
 *
 * No generator reads YAML. Only IR.
 */

import * as crypto from "crypto";
import type { IRDocument, Node } from "../constitution/ir/types";
import type { Generator, GeneratedArtifact } from "./types";
import type { CompilerDiagnostic } from "../compiler/diagnostics";
import { createDiagnostic } from "../compiler/diagnostics";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Capability Registry Generator
// ---------------------------------------------------------------------------

export class CapabilityRegistryGenerator implements Generator {
  readonly name = "CapabilityRegistryGenerator";

  supports(ir: IRDocument): boolean {
    return ir.nodes.some((n) => n.kind === "capability");
  }

  generate(ir: IRDocument): GeneratedArtifact[] {
    const artifacts: GeneratedArtifact[] = [];

    const capabilityNodes = ir.nodes.filter((n) => n.kind === "capability");

    // Generate capability definitions
    for (const node of capabilityNodes) {
      const name = node.symbol || node.id.replace("capability:", "");
      const content = generateCapabilityDefinition(name, node);
      artifacts.push({
        path: `capabilities/${pascalCase(name)}.ts`,
        content,
        hash: sha256(content),
        generator: this.name,
        description: `Canonical capability definition for ${name}`,
      });
    }

    // Generate capability registry
    const registryContent = generateCapabilityRegistry(capabilityNodes);
    artifacts.push({
      path: "capabilities/CapabilityRegistry.ts",
      content: registryContent,
      hash: sha256(registryContent),
      generator: this.name,
      description: "Capability registry with all capabilities",
    });

    return artifacts;
  }

  validate(artifacts: GeneratedArtifact[]): CompilerDiagnostic[] {
    const diagnostics: CompilerDiagnostic[] = [];

    for (const artifact of artifacts) {
      if (!artifact.content.includes("export")) {
        diagnostics.push(
          createDiagnostic({
            code: "G400",
            source_location: { file: artifact.path, line: 0, column: 0, length: 0 },
            message: `Generated file ${artifact.path} has no exports`,
          }),
        );
      }
    }

    return diagnostics;
  }

  snapshot(ir: IRDocument): string {
    const capabilityNames = ir.nodes
      .filter((n) => n.kind === "capability")
      .map((n) => n.symbol)
      .sort();
    return sha256(JSON.stringify({ generator: this.name, capabilities: capabilityNames }));
  }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function generateCapabilityDefinition(name: string, node: Node): string {
  const pascal = pascalCase(name);
  const contract = (node.properties.contract as string[]) ?? [];
  const description = (node.properties.description as string) ?? "";

  return `/**
 * ${pascal} — canonical capability definition.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 * Capability is abstract. Provider implements capability.
 */

export interface ${pascal}Capability {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly contract: readonly string[];
}

export const ${camelCase(name)}Capability: ${pascal}Capability = {
  id: "${camelCase(name)}",
  name: "${name}",
  description: "${description}",
  contract: ${JSON.stringify(contract)},
};

/** Type guard */
export function is${pascal}Capability(capability: { id: string }): capability is ${pascal}Capability {
  return capability.id === "${camelCase(name)}";
}
`;
}

function generateCapabilityRegistry(capabilityNodes: readonly Node[]): string {
  const capabilityEntries = capabilityNodes.map((n) => {
    const name = pascalCase(n.symbol || n.id.replace("capability:", ""));
    return `  ${camelCase(name)}: ${camelCase(name)}Capability,`;
  });

  const capabilityTypes = capabilityNodes.map((n) => {
    const name = pascalCase(n.symbol || n.id.replace("capability:", ""));
    return `  ${camelCase(name)}: ${name}Capability;`;
  });

  return `/**
 * CapabilityRegistry — canonical capability registry.
 *
 * DO NOT EDIT. Generated by CapabilityRegistryGenerator from Canonical IR.
 */

import { ${capabilityNodes.map((n) => pascalCase(n.symbol || n.id.replace("capability:", ""))).join(", ")} } from "./index";

export interface CapabilityRegistry {
${capabilityTypes.join("\n")}
}

export const capabilityRegistry: CapabilityRegistry = {
${capabilityEntries.join("\n")}
};

export type CapabilityId = keyof CapabilityRegistry;
`;
}
