/**
 * Projection Generator — IR → Projection skeletons.
 *
 * Generates projection classes with:
 *   - Registration
 *   - Indexes
 *   - Replay subscription
 *   - Tenant isolation
 *   - Version tracking
 *   - Rebuild hooks
 *
 * Business queries remain handwritten. Projection plumbing should not.
 *
 * No generator reads YAML. Only IR.
 */

import * as crypto from "crypto";
import type { IRDocument, Projection, Node, Edge } from "../constitution/ir/types";
import type { Generator, GeneratedArtifact } from "./types";
import type { CompilerDiagnostic } from "../compiler/diagnostics";
import { createDiagnostic } from "../compiler/diagnostics";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

/** Get events emitted by a given aggregate */
function getEventsForAggregate(aggregateNodeId: string, ir: IRDocument): string[] {
  return ir.edges
    .filter((e) => e.from === aggregateNodeId && e.kind === "emits")
    .map((e) => {
      const node = ir.nodes.find((n) => n.id === e.to);
      return node?.symbol ?? e.to.replace("event:", "");
    });
}

// ---------------------------------------------------------------------------
// Projection Generator
// ---------------------------------------------------------------------------

export class ProjectionGenerator implements Generator {
  readonly name = "ProjectionGenerator";

  supports(ir: IRDocument): boolean {
    // Generate projections for aggregates even if IR has no explicit projections
    return ir.nodes.some((n) => n.kind === "aggregate");
  }

  generate(ir: IRDocument): GeneratedArtifact[] {
    const artifacts: GeneratedArtifact[] = [];

    // Auto-generate projections for each aggregate (mission + identity)
    const aggregates = ir.nodes.filter(
      (n) => n.kind === "aggregate" && (n.id.startsWith("aggregate:") || n.id.startsWith("entity:")),
    );

    for (const agg of aggregates) {
      const name = agg.symbol || agg.id.replace(/^(aggregate|entity):/, "");
      const events = getEventsForAggregate(agg.id, ir);

      const content = generateProjectionClass(name, events);
      artifacts.push({
        path: `projections/${pascalCase(name)}Projection.ts`,
        content,
        hash: sha256(content),
        generator: this.name,
        description: `Projection skeleton for ${name} read model`,
      });
    }

    // Generate the projection registry
    if (aggregates.length > 0) {
      const registryContent = generateProjectionRegistry(aggregates);
      artifacts.push({
        path: "projections/ProjectionRegistry.ts",
        content: registryContent,
        hash: sha256(registryContent),
        generator: this.name,
        description: "Central registry of all projections",
      });
    }

    return artifacts;
  }

  validate(artifacts: GeneratedArtifact[]): CompilerDiagnostic[] {
    const diagnostics: CompilerDiagnostic[] = [];

    // Only validate projection classes, not the registry
    const projFiles = artifacts.filter(
      (a) => a.path.startsWith("projections/") && !a.path.endsWith("ProjectionRegistry.ts"),
    );

    for (const artifact of projFiles) {
      if (!artifact.content.includes("export class")) {
        diagnostics.push(
          createDiagnostic({
            code: "G500",
            source_location: { file: artifact.path, line: 0, column: 0, length: 0 },
            message: `Generated projection ${artifact.path} has no exported class`,
          }),
        );
      }
    }

    return diagnostics;
  }

  snapshot(ir: IRDocument): string {
    const aggNames = ir.nodes
      .filter((n) => n.kind === "aggregate")
      .map((n) => n.symbol)
      .sort();
    return sha256(JSON.stringify({ generator: this.name, projections: aggNames }));
  }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function generateProjectionClass(name: string, events: string[]): string {
  const pascal = pascalCase(name);
  const subscribesTo = events.length > 0
    ? events.map((e) => `"${pascalCase(e)}"`)
    : [];

  return `/**
 * ${pascal}Projection — read model projection.
 *
 * DO NOT EDIT. Generated by ProjectionGenerator from Canonical IR.
 * Business queries are handwritten. This file provides projection plumbing.
 *
 * Events subscribed: ${events.join(", ") || "none"}
 */

export interface ${pascal}ReadModel {
  readonly id: string;
  readonly tenantId: string;
  readonly version: number;
  readonly updatedAt: string;
  readonly data: Record<string, unknown>;
}

export interface ProjectionEvent {
  readonly type: string;
  readonly aggregateId: string;
  readonly tenantId: string;
  readonly timestamp: string;
  readonly payload: Record<string, unknown>;
}

/**
 * ${pascal}Projection — subscribes to events and builds a read model.
 */
export class ${pascal}Projection {
  /** Projection name (unique identifier) */
  readonly name = "${pascal}";

  /** Version of this projection schema */
  readonly version = 1;

  /** Events this projection subscribes to */
  readonly subscribesTo = [${subscribesTo.join(", ")}] as const;

  /** Indexes for efficient queries */
  readonly indexes = ["id", "tenantId", "version"] as const;

  /** Internal state */
  private readonly readModels = new Map<string, ${pascal}ReadModel>();

  /**
   * Handle a single event. Pure function: state + event → new state.
   */
  handle(model: ${pascal}ReadModel | null, event: ProjectionEvent): ${pascal}ReadModel {
    const previous = model ?? {
      id: event.aggregateId,
      tenantId: event.tenantId,
      version: 0,
      updatedAt: event.timestamp,
      data: {},
    };

    return {
      ...previous,
      version: previous.version + 1,
      updatedAt: event.timestamp,
      data: {
        ...previous.data,
        ...event.payload,
      },
    };
  }

  /**
   * Project an event into the read model store.
   */
  async project(event: ProjectionEvent): Promise<void> {
    const existing = this.readModels.get(event.aggregateId) ?? null;
    const updated = this.handle(existing, event);
    this.readModels.set(event.aggregateId, updated);
  }

  /**
   * Query a read model by ID.
   * Business-specific queries should be added as methods on this class.
   */
  async query(id: string): Promise<${pascal}ReadModel | null> {
    return this.readModels.get(id) ?? null;
  }

  /**
   * Query all read models for a tenant.
   */
  async queryByTenant(tenantId: string): Promise<readonly ${pascal}ReadModel[]> {
    return Array.from(this.readModels.values()).filter((m) => m.tenantId === tenantId);
  }

  /**
   * Tenant isolation boundary.
   * Ensures no cross-tenant data leakage.
   */
  async queryIsolated(id: string, tenantId: string): Promise<${pascal}ReadModel | null> {
    const model = this.readModels.get(id);
    if (!model || model.tenantId !== tenantId) return null;
    return model;
  }

  /**
   * Rebuild the projection from an event stream.
   * Used for schema migrations and replay-based rebuilds.
   */
  async rebuild(events: readonly ProjectionEvent[]): Promise<void> {
    this.readModels.clear();
    for (const event of events) {
      await this.project(event);
    }
  }

  /**
   * Take a snapshot of the projection state.
   */
  snapshot(): Record<string, ${pascal}ReadModel> {
    return Object.fromEntries(this.readModels);
  }

  /**
   * Restore from a snapshot.
   */
  restoreSnapshot(data: Record<string, ${pascal}ReadModel>): void {
    this.readModels.clear();
    for (const [key, value] of Object.entries(data)) {
      this.readModels.set(key, value);
    }
  }
}
`;
}

function generateProjectionRegistry(aggregates: readonly Node[]): string {
  const imports = aggregates.map((agg) => {
    const name = agg.symbol || agg.id.replace(/^(aggregate|entity):/, "");
    const pascal = pascalCase(name);
    return `import { ${pascal}Projection } from "./${pascal}Projection";`;
  });

  const instances = aggregates.map((agg) => {
    const name = agg.symbol || agg.id.replace(/^(aggregate|entity):/, "");
    const pascal = pascalCase(name);
    return `  ${camelCase(name)}: new ${pascal}Projection(),`;
  });

  return `/**
 * ProjectionRegistry — central registry of all projections.
 *
 * DO NOT EDIT. Generated by ProjectionGenerator from Canonical IR.
 */

${imports.join("\n")}

export interface Projection {
  readonly name: string;
  readonly version: number;
  readonly subscribesTo: readonly string[];
  readonly indexes: readonly string[];
  project(event: { type: string; aggregateId: string; tenantId: string; timestamp: string; payload: Record<string, unknown> }): Promise<void>;
  rebuild(events: { type: string; aggregateId: string; tenantId: string; timestamp: string; payload: Record<string, unknown> }[]): Promise<void>;
}

/** All registered projections */
export const PROJECTIONS: Record<string, Projection> = {
${instances.join("\n")}
};

/** Get a projection by name */
export function getProjection(name: string): Projection | undefined {
  return PROJECTIONS[name];
}

/** Get all projection names */
export function getProjectionNames(): string[] {
  return Object.keys(PROJECTIONS);
}

/** Route an event to all subscribed projections */
export async function routeEvent(event: { type: string; [key: string]: unknown }): Promise<void> {
  const eventType = (event as { type: string }).type;
  for (const projection of Object.values(PROJECTIONS)) {
    if (projection.subscribesTo.includes(eventType)) {
      await projection.project(event as { type: string; aggregateId: string; tenantId: string; timestamp: string; payload: Record<string, unknown> });
    }
  }
}
`;
}
