/**
 * Provider Registry Generator — IR → Canonical provider registry metadata.
 *
 * Generates provider metadata (NOT constructors).
 * PING constructs runtime objects. Generator only generates metadata.
 *
 * No generator reads YAML. Only IR.
 */

import * as crypto from "crypto";
import type { IRDocument, Node } from "../constitution/ir/types";
import type { Generator, GeneratedArtifact } from "./types";
import type { CompilerDiagnostic } from "../compiler/diagnostics";
import { createDiagnostic } from "../compiler/diagnostics";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Provider Registry Generator
// ---------------------------------------------------------------------------

export class ProviderRegistryGenerator implements Generator {
  readonly name = "ProviderRegistryGenerator";

  supports(ir: IRDocument): boolean {
    return ir.nodes.some((n) => n.kind === "capability");
  }

  generate(ir: IRDocument): GeneratedArtifact[] {
    const artifacts: GeneratedArtifact[] = [];

    const capabilityNodes = ir.nodes.filter((n) => n.kind === "capability");

    // Generate provider metadata (NOT constructors) from capabilities
    for (const node of capabilityNodes) {
      const name = node.symbol || node.id.replace("capability:", "");
      const content = generateProviderMetadata(name, node);
      artifacts.push({
        path: `providers/${pascalCase(name)}.ts`,
        content,
        hash: sha256(content),
        generator: this.name,
        description: `Canonical provider metadata for ${name}`,
      });
    }

    // Generate provider registry
    const registryContent = generateProviderRegistry(capabilityNodes);
    artifacts.push({
      path: "providers/ProviderRegistry.ts",
      content: registryContent,
      hash: sha256(registryContent),
      generator: this.name,
      description: "Provider registry with all provider metadata",
    });

    return artifacts;
  }

  validate(artifacts: GeneratedArtifact[]): CompilerDiagnostic[] {
    const diagnostics: CompilerDiagnostic[] = [];

    for (const artifact of artifacts) {
      if (!artifact.content.includes("export")) {
        diagnostics.push(
          createDiagnostic({
            code: "G500",
            source_location: { file: artifact.path, line: 0, column: 0, length: 0 },
            message: `Generated file ${artifact.path} has no exports`,
          }),
        );
      }
    }

    // Verify no constructors are generated
    for (const artifact of artifacts) {
      if (artifact.content.includes("constructor(") || /new\s+[A-Z]/.test(artifact.content)) {
        diagnostics.push(
          createDiagnostic({
            code: "G501",
            source_location: { file: artifact.path, line: 0, column: 0, length: 0 },
            message: `Provider metadata should not contain constructors: ${artifact.path}`,
          }),
        );
      }
    }

    return diagnostics;
  }

  snapshot(ir: IRDocument): string {
    const capabilityNames = ir.nodes
      .filter((n) => n.kind === "capability")
      .map((n) => n.symbol)
      .sort();
    return sha256(JSON.stringify({ generator: this.name, capabilities: capabilityNames }));
  }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function generateProviderMetadata(name: string, node: Node): string {
  const pascal = pascalCase(name);
  const contract = (node.properties.contract as string[]) ?? [];
  const priority = (node.properties.priority as string) ?? "secondary";
  const region = (node.properties.region as string) ?? "global";
  const configSchema = (node.properties.configSchema as Record<string, unknown>) ?? {};

  return `/**
 * ${pascal} — canonical provider metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects.
 * Only metadata: capabilities, priority, configuration schema.
 */

export interface ${pascal}ProviderMetadata {
  readonly id: string;
  readonly name: string;
  readonly capabilities: readonly string[];
  readonly priority: "primary" | "secondary" | "tertiary";
  readonly region: string;
  readonly configSchema: Record<string, unknown>;
}

export const ${camelCase(name)}ProviderMetadata: ${pascal}ProviderMetadata = {
  id: "${camelCase(name)}",
  name: "${name}",
  capabilities: ${JSON.stringify(contract)},
  priority: "${priority}",
  region: "${region}",
  configSchema: ${JSON.stringify(configSchema)},
};

/** Type guard */
export function is${pascal}ProviderMetadata(metadata: { id: string }): metadata is ${pascal}ProviderMetadata {
  return metadata.id === "${camelCase(name)}";
}
`;
}

function generateProviderRegistry(providerNodes: readonly Node[]): string {
  const providerEntries = providerNodes.map((n) => {
    const name = pascalCase(n.symbol || n.id.replace("provider:", ""));
    return `  ${camelCase(name)}: ${camelCase(name)}ProviderMetadata,`;
  });

  const providerTypes = providerNodes.map((n) => {
    const name = pascalCase(n.symbol || n.id.replace("provider:", ""));
    return `  ${camelCase(name)}: ${name}ProviderMetadata;`;
  });

  return `/**
 * ProviderRegistry — canonical provider registry metadata.
 *
 * DO NOT EDIT. Generated by ProviderRegistryGenerator from Canonical IR.
 * NO constructors. PING constructs runtime objects from this metadata.
 */

import { ${providerNodes.map((n) => pascalCase(n.symbol || n.id.replace("provider:", ""))).join(", ")} } from "./index";

export interface ProviderRegistry {
${providerTypes.join("\n")}
}

export const providerRegistry: ProviderRegistry = {
${providerEntries.join("\n")}
};

export type ProviderId = keyof ProviderRegistry;
`;
}
