/**
 * State Machine Generator — IR → Canonical state machine definitions.
 *
 * Every state machine gets one canonical definition with:
 *   - States, transitions, guards, events
 *   - State machine IR for generation
 *   - Generated state machine artifacts
 *
 * No generator reads YAML. Only IR.
 */

import * as crypto from "crypto";
import type { IRDocument, Node } from "../constitution/ir/types";
import type { Generator, GeneratedArtifact } from "./types";
import type { CompilerDiagnostic } from "../compiler/diagnostics";
import { createDiagnostic } from "../compiler/diagnostics";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// State Machine Generator
// ---------------------------------------------------------------------------

export class StateMachineGenerator implements Generator {
  readonly name = "StateMachineGenerator";

  supports(ir: IRDocument): boolean {
    return ir.nodes.some((n) => n.kind === "aggregate");
  }

  generate(ir: IRDocument): GeneratedArtifact[] {
    const artifacts: GeneratedArtifact[] = [];

    const aggregateNodes = ir.nodes.filter((n) => n.kind === "aggregate");

    // Generate state machine definitions for each aggregate
    for (const node of aggregateNodes) {
      const name = node.symbol || node.id.replace("aggregate:", "");
      const content = generateStateMachineDefinition(name, node);
      artifacts.push({
        path: `state-machines/${pascalCase(name)}StateMachine.ts`,
        content,
        hash: sha256(content),
        generator: this.name,
        description: `Canonical state machine for ${name}`,
      });
    }

    // Generate state machine IR
    const irContent = generateStateMachineIR(aggregateNodes);
    artifacts.push({
      path: "state-machines/StateMachineIR.ts",
      content: irContent,
      hash: sha256(irContent),
      generator: this.name,
      description: "State machine intermediate representation",
    });

    return artifacts;
  }

  validate(artifacts: GeneratedArtifact[]): CompilerDiagnostic[] {
    const diagnostics: CompilerDiagnostic[] = [];

    for (const artifact of artifacts) {
      if (!artifact.content.includes("export")) {
        diagnostics.push(
          createDiagnostic({
            code: "G600",
            source_location: { file: artifact.path, line: 0, column: 0, length: 0 },
            message: `Generated file ${artifact.path} has no exports`,
          }),
        );
      }
    }

    return diagnostics;
  }

  snapshot(ir: IRDocument): string {
    const aggregateNames = ir.nodes
      .filter((n) => n.kind === "aggregate")
      .map((n) => n.symbol)
      .sort();
    return sha256(JSON.stringify({ generator: this.name, aggregates: aggregateNames }));
  }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function generateStateMachineDefinition(name: string, node: Node): string {
  const pascal = pascalCase(name);
  const states = (node.properties.states as string[]) ?? ["initial", "active", "completed"];
  const events = getEventsForAggregate(node.id);

  return `/**
 * ${pascal}StateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: ${pascal}
 */

export type ${pascal}State = ${states.map((s) => `"${s}"`).join(" | ")};

export interface ${pascal}StateMachine {
  readonly currentState: ${pascal}State;
  readonly transitions: readonly ${pascal}Transition[];
}

export interface ${pascal}Transition {
  readonly from: ${pascal}State;
  readonly to: ${pascal}State;
  readonly event: string;
  readonly guard?: string;
}

export const ${camelCase(name)}StateMachine: ${pascal}StateMachine = {
  currentState: "initial",
  transitions: [
${events.map((event) => `    { from: "initial", to: "active", event: "${event}" },`).join("\n")}
  ],
};

/** Type guard */
export function is${pascal}StateMachine(machine: { currentState: string }): machine is ${pascal}StateMachine {
  return ${states.map((s) => `machine.currentState === "${s}"`).join(" || ")};
}
`;
}

function getEventsForAggregate(aggregateId: string): string[] {
  // This would normally come from IR edges
  // For now, return common events
  return ["Created", "Updated", "Completed", "Cancelled"];
}

function generateStateMachineIR(aggregateNodes: readonly Node[]): string {
  const machineEntries = aggregateNodes.map((n) => {
    const name = pascalCase(n.symbol || n.id.replace("aggregate:", ""));
    const states = (n.properties.states as string[]) ?? ["initial", "active", "completed"];
    return `  {
    aggregate: "${name}",
    states: ${JSON.stringify(states)},
    transitions: [],
  }`;
  });

  return `/**
 * StateMachineIR — canonical state machine intermediate representation.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 */

export interface StateMachineIR {
  readonly aggregate: string;
  readonly states: readonly string[];
  readonly transitions: readonly StateMachineIRTransition[];
}

export interface StateMachineIRTransition {
  readonly from: string;
  readonly to: string;
  readonly event: string;
  readonly guard?: string;
}

export const stateMachineIR: readonly StateMachineIR[] = [
${machineEntries.join(',\n')}
];
`;
}
