/**
 * Workflow Generator — IR → Canonical workflow definitions.
 *
 * Every workflow gets one canonical definition with:
 *   - Mission, Intent, Workflow Definition
 *   - Workflow Graph (steps, dependencies, transitions)
 *   - Workflow IR for generation
 *   - Generated workflow artifacts
 *
 * No generator reads YAML. Only IR.
 */

import * as crypto from "crypto";
import type { IRDocument, Node } from "../constitution/ir/types";
import type { Generator, GeneratedArtifact } from "./types";
import type { CompilerDiagnostic } from "../compiler/diagnostics";
import { createDiagnostic } from "../compiler/diagnostics";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Workflow Generator
// ---------------------------------------------------------------------------

export class WorkflowGenerator implements Generator {
  readonly name = "WorkflowGenerator";

  supports(ir: IRDocument): boolean {
    return ir.nodes.some((n) => n.kind === "workflow");
  }

  generate(ir: IRDocument): GeneratedArtifact[] {
    const artifacts: GeneratedArtifact[] = [];

    const workflowNodes = ir.nodes.filter((n) => n.kind === "workflow");

    // Generate workflow definitions
    for (const node of workflowNodes) {
      const name = node.symbol || node.id.replace("workflow:", "");
      const content = generateWorkflowDefinition(name, node);
      artifacts.push({
        path: `workflows/${pascalCase(name)}.ts`,
        content,
        hash: sha256(content),
        generator: this.name,
        description: `Canonical workflow definition for ${name}`,
      });
    }

    // Generate workflow graph
    const graphContent = generateWorkflowGraph(workflowNodes);
    artifacts.push({
      path: "workflows/WorkflowGraph.ts",
      content: graphContent,
      hash: sha256(graphContent),
      generator: this.name,
      description: "Workflow graph with step dependencies",
    });

    // Generate workflow IR
    const irContent = generateWorkflowIR(workflowNodes);
    artifacts.push({
      path: "workflows/WorkflowIR.ts",
      content: irContent,
      hash: sha256(irContent),
      generator: this.name,
      description: "Workflow intermediate representation",
    });

    return artifacts;
  }

  validate(artifacts: GeneratedArtifact[]): CompilerDiagnostic[] {
    const diagnostics: CompilerDiagnostic[] = [];

    for (const artifact of artifacts) {
      if (!artifact.content.includes("export")) {
        diagnostics.push(
          createDiagnostic({
            code: "G300",
            source_location: { file: artifact.path, line: 0, column: 0, length: 0 },
            message: `Generated file ${artifact.path} has no exports`,
          }),
        );
      }
    }

    // Verify workflow graph has all required fields
    const graph = artifacts.find((a) => a.path.endsWith("WorkflowGraph.ts"));
    if (graph) {
      const requiredFields = ["steps", "dependencies", "transitions"];
      for (const field of requiredFields) {
        if (!graph.content.includes(field)) {
          diagnostics.push(
            createDiagnostic({
              code: "G301",
              source_location: { file: graph.path, line: 0, column: 0, length: 0 },
              message: `WorkflowGraph is missing required field: ${field}`,
            }),
          );
        }
      }
    }

    return diagnostics;
  }

  snapshot(ir: IRDocument): string {
    const workflowNames = ir.nodes
      .filter((n) => n.kind === "workflow")
      .map((n) => n.symbol)
      .sort();
    return sha256(JSON.stringify({ generator: this.name, workflows: workflowNames }));
  }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function generateWorkflowDefinition(name: string, node: Node): string {
  const pascal = pascalCase(name);
  const mission = (node.properties.mission as string) ?? "Unknown";
  const intent = (node.properties.intent as string) ?? "Unknown";

  return `/**
 * ${pascal} — canonical workflow definition.
 *
 * DO NOT EDIT. Generated by WorkflowGenerator from Canonical IR.
 * Mission: ${mission}
 * Intent: ${intent}
 */

export interface ${pascal}Workflow {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly mission: string;
  readonly intent: string;
  readonly steps: readonly WorkflowStep[];
  readonly dependencies: readonly WorkflowDependency[];
}

export interface WorkflowStep {
  readonly id: string;
  readonly name: string;
  readonly capability: string;
  readonly taskTemplate?: TaskTemplate;
}

export interface TaskTemplate {
  readonly title: string;
  readonly description: string;
  readonly status: string;
}

export interface WorkflowDependency {
  readonly from: string;
  readonly to: string;
  readonly condition?: string;
}

/** Type guard */
export function is${pascal}Workflow(workflow: { id: string }): workflow is ${pascal}Workflow {
  return workflow.id === "${camelCase(name)}";
}
`;
}

function generateWorkflowGraph(workflowNodes: readonly Node[]): string {
  const workflowEntries = workflowNodes.map((n) => {
    const name = pascalCase(n.symbol || n.id.replace("workflow:", ""));
    return `  ${camelCase(name)}: ${name}Workflow;`;
  });

  return `/**
 * WorkflowGraph — canonical workflow graph with step dependencies.
 *
 * DO NOT EDIT. Generated by WorkflowGenerator from Canonical IR.
 */

export interface WorkflowGraph {
  readonly steps: readonly WorkflowStep[];
  readonly dependencies: readonly WorkflowDependency[];
  readonly transitions: readonly WorkflowTransition[];
}

export interface WorkflowStep {
  readonly id: string;
  readonly name: string;
  readonly capability: string;
}

export interface WorkflowDependency {
  readonly from: string;
  readonly to: string;
  readonly condition?: string;
}

export interface WorkflowTransition {
  readonly from: string;
  readonly to: string;
  readonly trigger: string;
}

${workflowEntries.length > 0 ? `export const workflowGraph: WorkflowGraph = {
  steps: [],
  dependencies: [],
  transitions: [],
};` : ''}
`;
}

function generateWorkflowIR(workflowNodes: readonly Node[]): string {
  const workflowEntries = workflowNodes.map((n) => {
    const name = pascalCase(n.symbol || n.id.replace("workflow:", ""));
    const mission = (n.properties.mission as string) ?? "Unknown";
    const intent = (n.properties.intent as string) ?? "Unknown";
    return `  {
    id: "${camelCase(name)}",
    name: "${name}",
    mission: "${mission}",
    intent: "${intent}",
    steps: [],
    dependencies: [],
  }`;
  });

  return `/**
 * WorkflowIR — canonical workflow intermediate representation.
 *
 * DO NOT EDIT. Generated by WorkflowGenerator from Canonical IR.
 */

export interface WorkflowIR {
  readonly id: string;
  readonly name: string;
  readonly mission: string;
  readonly intent: string;
  readonly steps: readonly WorkflowIRStep[];
  readonly dependencies: readonly WorkflowIRDependency[];
}

export interface WorkflowIRStep {
  readonly id: string;
  readonly name: string;
  readonly capability: string;
}

export interface WorkflowIRDependency {
  readonly from: string;
  readonly to: string;
  readonly condition?: string;
}

export const workflowIR: readonly WorkflowIR[] = [
${workflowEntries.join(',\n')}
];
`;
}
