/**
 * CrewRepository — generated from Canonical IR.
 *
 * DO NOT EDIT. Generated by RepositoryGenerator from Canonical IR.
 * Compiler: 1.0.0
 * Constitution: 1.0.0
 * Hash: f4588d986def983b4f2283bcf71f738e5113bc69373d70a330e7fca1aca71275
 * Aggregate: Crew
 * Authority: IdentityAuthority
 * Events: none
 * Commands: none
 */

import type { IRDocument } from "../../constitution/ir/types";

// ---------------------------------------------------------------------------
// Aggregate State
// ---------------------------------------------------------------------------

export enum CrewStateStatus {
  Initial = "initial"
}

export interface CrewState {
  readonly id: string;
  readonly version: number;
  readonly status: CrewStateStatus;
  readonly authority: string;
  readonly events: readonly ({ type: string })[];
}

// ---------------------------------------------------------------------------
// Aggregate Factory
// ---------------------------------------------------------------------------

export class CrewAggregate {
  /** Create initial aggregate state */
  static initial(id: string): CrewState {
    return {
      id,
      version: 0,
      status: CrewStateStatus.Initial,
      authority: "IdentityAuthority",
      events: [],
    };
  }
  
  /** Create aggregate from event stream */
  static fromEvents(id: string, events: readonly { type: string }[]): CrewState {
    let state = CrewAggregate.initial(id);
    for (const event of events) {
      state = CrewRepository.apply(state, event);
    }
    return state;
  }
}

// ---------------------------------------------------------------------------
// Event Types
// ---------------------------------------------------------------------------



export type CrewEvent = { type: string };

// ---------------------------------------------------------------------------
// Event Stream Interface
// ---------------------------------------------------------------------------

export interface EventStream {
  readonly aggregateId: string;
  readonly events: readonly CrewEvent[];
  readonly version: number;
}

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

export class CrewRepository {
  private readonly authority = "IdentityAuthority";

  /**
   * Load an aggregate by replaying its event stream.
   */
  async load(aggregateId: string): Promise<CrewState | null> {
    const stream = await this.loadEventStream(aggregateId);
    if (stream.events.length === 0) return null;

    return CrewAggregate.fromEvents(aggregateId, stream.events);
  }

  /**
   * Save new events for an aggregate.
   * Events are append-only; state is derived at read time.
   */
  async save(state: CrewState, events: CrewEvent[]): Promise<void> {
    if (events.length === 0) return;
    await this.appendToStream(state.id, events, state.version);
  }

  /**
   * Apply a single event to the current state.
   * This is the pure function: state + event → new state.
   * Static — callable without an instance (used by replay dispatch).
   */
  static apply(state: CrewState, event: CrewEvent): CrewState {
    switch (event.type) {

      default:
        return state;
    }
  }

  // -------------------------------------------------------------------------
  // Event applicators (one per event type)
  // -------------------------------------------------------------------------



  // -------------------------------------------------------------------------
  // Snapshot interface (stub — Sprint 2 future)
  // -------------------------------------------------------------------------

  /**
   * Take a snapshot of the current state.
   * Stub: returns state as-is. Implement snapshot storage in production.
   */
  async snapshot(state: CrewState): Promise<CrewState> {
    return state;
  }

  /**
   * Load from snapshot + replay remaining events.
   * Stub: ignores snapshot, loads from event stream.
   */
  async loadFromSnapshot(_snapshotId: string, aggregateId: string): Promise<CrewState | null> {
    return this.load(aggregateId);
  }

  // -------------------------------------------------------------------------
  // Authority hook interface
  // -------------------------------------------------------------------------

  /**
   * Called before a command is executed.
   * Return true to allow, false to reject.
   * Stub: always allows. Wire to authority policies in production.
   */
  async beforeCommand(_command: string, _aggregateId: string, _tenantId: string): Promise<boolean> {
    return true;
  }

  /**
   * Called after events are persisted.
   * Stub: no-op. Wire to projection/notification in production.
   */
  async afterSave(_state: CrewState, _events: CrewEvent[]): Promise<void> {
    // Wire to projections here
  }

  /**
   * Register a projection for this aggregate.
   * Stub: no-op. Wire to projection registry in production.
   */
  async registerProjection(_name: string, _handler: unknown): Promise<void> {
    // Wire to projection registry here
  }

  // -------------------------------------------------------------------------
  // Internal (stub implementations — wire to event store in production)
  // -------------------------------------------------------------------------

  protected async loadEventStream(aggregateId: string): Promise<EventStream> {
    // TODO: Wire to event store
    return { aggregateId, events: [], version: 0 };
  }

  protected async appendToStream(
    _aggregateId: string,
    _events: CrewEvent[],
    _expectedVersion: number,
  ): Promise<void> {
    // TODO: Wire to event store
  }
}
