/**
 * CustomerRepository — generated from Canonical IR.
 *
 * DO NOT EDIT. Generated by RepositoryGenerator from Canonical IR.
 * Compiler: 1.0.0
 * Constitution: 1.0.0
 * Hash: 2cc21a63427d4e25ccc22a5fc667f6e1b6cfa879a916e4b3d17fa04fda2f3986
 * Aggregate: Customer
 * Authority: IdentityAuthority
 * Events: none
 * Commands: none
 */

import type { IRDocument } from "../../constitution/ir/types";

// ---------------------------------------------------------------------------
// Aggregate State
// ---------------------------------------------------------------------------

export enum CustomerStateStatus {
  Initial = "initial"
}

export interface CustomerState {
  readonly id: string;
  readonly version: number;
  readonly status: CustomerStateStatus;
  readonly authority: string;
  readonly events: readonly ({ type: string })[];
}

// ---------------------------------------------------------------------------
// Aggregate Factory
// ---------------------------------------------------------------------------

export class CustomerAggregate {
  /** Create initial aggregate state */
  static initial(id: string): CustomerState {
    return {
      id,
      version: 0,
      status: CustomerStateStatus.Initial,
      authority: "IdentityAuthority",
      events: [],
    };
  }
  
  /** Create aggregate from event stream */
  static fromEvents(id: string, events: readonly { type: string }[]): CustomerState {
    let state = CustomerAggregate.initial(id);
    for (const event of events) {
      state = CustomerRepository.apply(state, event);
    }
    return state;
  }
}

// ---------------------------------------------------------------------------
// Event Types
// ---------------------------------------------------------------------------



export type CustomerEvent = { type: string };

// ---------------------------------------------------------------------------
// Event Stream Interface
// ---------------------------------------------------------------------------

export interface EventStream {
  readonly aggregateId: string;
  readonly events: readonly CustomerEvent[];
  readonly version: number;
}

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

export class CustomerRepository {
  private readonly authority = "IdentityAuthority";

  /**
   * Load an aggregate by replaying its event stream.
   */
  async load(aggregateId: string): Promise<CustomerState | null> {
    const stream = await this.loadEventStream(aggregateId);
    if (stream.events.length === 0) return null;

    return CustomerAggregate.fromEvents(aggregateId, stream.events);
  }

  /**
   * Save new events for an aggregate.
   * Events are append-only; state is derived at read time.
   */
  async save(state: CustomerState, events: CustomerEvent[]): Promise<void> {
    if (events.length === 0) return;
    await this.appendToStream(state.id, events, state.version);
  }

  /**
   * Apply a single event to the current state.
   * This is the pure function: state + event → new state.
   * Static — callable without an instance (used by replay dispatch).
   */
  static apply(state: CustomerState, event: CustomerEvent): CustomerState {
    switch (event.type) {

      default:
        return state;
    }
  }

  // -------------------------------------------------------------------------
  // Event applicators (one per event type)
  // -------------------------------------------------------------------------



  // -------------------------------------------------------------------------
  // Snapshot interface (stub — Sprint 2 future)
  // -------------------------------------------------------------------------

  /**
   * Take a snapshot of the current state.
   * Stub: returns state as-is. Implement snapshot storage in production.
   */
  async snapshot(state: CustomerState): Promise<CustomerState> {
    return state;
  }

  /**
   * Load from snapshot + replay remaining events.
   * Stub: ignores snapshot, loads from event stream.
   */
  async loadFromSnapshot(_snapshotId: string, aggregateId: string): Promise<CustomerState | null> {
    return this.load(aggregateId);
  }

  // -------------------------------------------------------------------------
  // Authority hook interface
  // -------------------------------------------------------------------------

  /**
   * Called before a command is executed.
   * Return true to allow, false to reject.
   * Stub: always allows. Wire to authority policies in production.
   */
  async beforeCommand(_command: string, _aggregateId: string, _tenantId: string): Promise<boolean> {
    return true;
  }

  /**
   * Called after events are persisted.
   * Stub: no-op. Wire to projection/notification in production.
   */
  async afterSave(_state: CustomerState, _events: CustomerEvent[]): Promise<void> {
    // Wire to projections here
  }

  /**
   * Register a projection for this aggregate.
   * Stub: no-op. Wire to projection registry in production.
   */
  async registerProjection(_name: string, _handler: unknown): Promise<void> {
    // Wire to projection registry here
  }

  // -------------------------------------------------------------------------
  // Internal (stub implementations — wire to event store in production)
  // -------------------------------------------------------------------------

  protected async loadEventStream(aggregateId: string): Promise<EventStream> {
    // TODO: Wire to event store
    return { aggregateId, events: [], version: 0 };
  }

  protected async appendToStream(
    _aggregateId: string,
    _events: CustomerEvent[],
    _expectedVersion: number,
  ): Promise<void> {
    // TODO: Wire to event store
  }
}
