/**
 * JobRepository — generated from Canonical IR.
 *
 * DO NOT EDIT. Generated by RepositoryGenerator from Canonical IR.
 * Compiler: 1.0.0
 * Constitution: 1.0.0
 * Hash: 92858789cfc6b8ecee7f1e42a4979b100072d77332dbe731587f4d93bc5d48cb
 * Aggregate: Job
 * Authority: JobAuthority
 * Events: JobCreated, CrewAssigned, JobCompleted
 * Commands: AssignCrew, Complete
 */

import type { IRDocument } from "../../constitution/ir/types";

// ---------------------------------------------------------------------------
// Aggregate State
// ---------------------------------------------------------------------------

export enum JobStateStatus {
  JobCreated = "JobCreated",
  CrewAssigned = "CrewAssigned",
  JobCompleted = "JobCompleted"
}

export interface JobState {
  readonly id: string;
  readonly version: number;
  readonly status: JobStateStatus;
  readonly authority: string;
  readonly events: readonly (JobCreated | CrewAssigned | JobCompleted)[];
}

// ---------------------------------------------------------------------------
// Aggregate Factory
// ---------------------------------------------------------------------------

export class JobAggregate {
  /** Create initial aggregate state */
  static initial(id: string): JobState {
    return {
      id,
      version: 0,
      status: JobStateStatus.Initial,
      authority: "JobAuthority",
      events: [],
    };
  }
  
  /** Create aggregate from event stream */
  static fromEvents(id: string, events: readonly JobCreated | CrewAssigned | JobCompleted[]): JobState {
    let state = JobAggregate.initial(id);
    for (const event of events) {
      state = JobRepository.apply(state, event);
    }
    return state;
  }
}

// ---------------------------------------------------------------------------
// Event Types
// ---------------------------------------------------------------------------

export interface JobCreated {
  readonly type: "JobCreated";
  readonly aggregateId: string;
  readonly authorityId: string;
  readonly tenantId: string;
  readonly replaySequence: number;
  readonly witnessId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly schemaVersion: string;
  readonly timestamp: string;
  readonly contentHash: string;
}

export interface CrewAssigned {
  readonly type: "CrewAssigned";
  readonly aggregateId: string;
  readonly authorityId: string;
  readonly tenantId: string;
  readonly replaySequence: number;
  readonly witnessId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly schemaVersion: string;
  readonly timestamp: string;
  readonly contentHash: string;
}

export interface JobCompleted {
  readonly type: "JobCompleted";
  readonly aggregateId: string;
  readonly authorityId: string;
  readonly tenantId: string;
  readonly replaySequence: number;
  readonly witnessId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly schemaVersion: string;
  readonly timestamp: string;
  readonly contentHash: string;
}

export type JobEvent = JobCreated | CrewAssigned | JobCompleted;

// ---------------------------------------------------------------------------
// Event Stream Interface
// ---------------------------------------------------------------------------

export interface EventStream {
  readonly aggregateId: string;
  readonly events: readonly JobEvent[];
  readonly version: number;
}

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

export class JobRepository {
  private readonly authority = "JobAuthority";

  /**
   * Load an aggregate by replaying its event stream.
   */
  async load(aggregateId: string): Promise<JobState | null> {
    const stream = await this.loadEventStream(aggregateId);
    if (stream.events.length === 0) return null;

    return JobAggregate.fromEvents(aggregateId, stream.events);
  }

  /**
   * Save new events for an aggregate.
   * Events are append-only; state is derived at read time.
   */
  async save(state: JobState, events: JobEvent[]): Promise<void> {
    if (events.length === 0) return;
    await this.appendToStream(state.id, events, state.version);
  }

  /**
   * Apply a single event to the current state.
   * This is the pure function: state + event → new state.
   * Static — callable without an instance (used by replay dispatch).
   */
  static apply(state: JobState, event: JobEvent): JobState {
    switch (event.type) {
      case "JobCreated":
        return JobRepository.applyJobCreated(state, event);
      case "CrewAssigned":
        return JobRepository.applyCrewAssigned(state, event);
      case "JobCompleted":
        return JobRepository.applyJobCompleted(state, event);
      default:
        return state;
    }
  }

  // -------------------------------------------------------------------------
  // Event applicators (one per event type)
  // -------------------------------------------------------------------------

  private static applyJobCreated(state: JobState, event: JobCreated): JobState {
    return {
      ...state,
      version: state.version + 1,
      events: [...state.events, event],
      status: "jobCreated",
    };
  }

  private static applyCrewAssigned(state: JobState, event: CrewAssigned): JobState {
    return {
      ...state,
      version: state.version + 1,
      events: [...state.events, event],
      status: "crewAssigned",
    };
  }

  private static applyJobCompleted(state: JobState, event: JobCompleted): JobState {
    return {
      ...state,
      version: state.version + 1,
      events: [...state.events, event],
      status: "jobCompleted",
    };
  }

  // -------------------------------------------------------------------------
  // Snapshot interface (stub — Sprint 2 future)
  // -------------------------------------------------------------------------

  /**
   * Take a snapshot of the current state.
   * Stub: returns state as-is. Implement snapshot storage in production.
   */
  async snapshot(state: JobState): Promise<JobState> {
    return state;
  }

  /**
   * Load from snapshot + replay remaining events.
   * Stub: ignores snapshot, loads from event stream.
   */
  async loadFromSnapshot(_snapshotId: string, aggregateId: string): Promise<JobState | null> {
    return this.load(aggregateId);
  }

  // -------------------------------------------------------------------------
  // Authority hook interface
  // -------------------------------------------------------------------------

  /**
   * Called before a command is executed.
   * Return true to allow, false to reject.
   * Stub: always allows. Wire to authority policies in production.
   */
  async beforeCommand(_command: string, _aggregateId: string, _tenantId: string): Promise<boolean> {
    return true;
  }

  /**
   * Called after events are persisted.
   * Stub: no-op. Wire to projection/notification in production.
   */
  async afterSave(_state: JobState, _events: JobEvent[]): Promise<void> {
    // Wire to projections here
  }

  /**
   * Register a projection for this aggregate.
   * Stub: no-op. Wire to projection registry in production.
   */
  async registerProjection(_name: string, _handler: unknown): Promise<void> {
    // Wire to projection registry here
  }

  // -------------------------------------------------------------------------
  // Internal (stub implementations — wire to event store in production)
  // -------------------------------------------------------------------------

  protected async loadEventStream(aggregateId: string): Promise<EventStream> {
    // TODO: Wire to event store
    return { aggregateId, events: [], version: 0 };
  }

  protected async appendToStream(
    _aggregateId: string,
    _events: JobEvent[],
    _expectedVersion: number,
  ): Promise<void> {
    // TODO: Wire to event store
  }
}
