/**
 * ProjectRepository — generated from Canonical IR.
 *
 * DO NOT EDIT. Generated by RepositoryGenerator from Canonical IR.
 * Compiler: 1.0.0
 * Constitution: 1.0.0
 * Hash: 94165514863e28720ae0fb5282916e3b64291b4513e134e0cba26e00c0415d1e
 * Aggregate: Project
 * Authority: ProjectAuthority
 * Events: ProjectCreated, ProjectCompleted
 * Commands: none
 */

import type { IRDocument } from "../../constitution/ir/types";

// ---------------------------------------------------------------------------
// Aggregate State
// ---------------------------------------------------------------------------

export enum ProjectStateStatus {
  ProjectCreated = "ProjectCreated",
  ProjectCompleted = "ProjectCompleted"
}

export interface ProjectState {
  readonly id: string;
  readonly version: number;
  readonly status: ProjectStateStatus;
  readonly authority: string;
  readonly events: readonly (ProjectCreated | ProjectCompleted)[];
}

// ---------------------------------------------------------------------------
// Aggregate Factory
// ---------------------------------------------------------------------------

export class ProjectAggregate {
  /** Create initial aggregate state */
  static initial(id: string): ProjectState {
    return {
      id,
      version: 0,
      status: ProjectStateStatus.Initial,
      authority: "ProjectAuthority",
      events: [],
    };
  }
  
  /** Create aggregate from event stream */
  static fromEvents(id: string, events: readonly ProjectCreated | ProjectCompleted[]): ProjectState {
    let state = ProjectAggregate.initial(id);
    for (const event of events) {
      state = ProjectRepository.apply(state, event);
    }
    return state;
  }
}

// ---------------------------------------------------------------------------
// Event Types
// ---------------------------------------------------------------------------

export interface ProjectCreated {
  readonly type: "ProjectCreated";
  readonly aggregateId: string;
  readonly authorityId: string;
  readonly tenantId: string;
  readonly replaySequence: number;
  readonly witnessId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly schemaVersion: string;
  readonly timestamp: string;
  readonly contentHash: string;
}

export interface ProjectCompleted {
  readonly type: "ProjectCompleted";
  readonly aggregateId: string;
  readonly authorityId: string;
  readonly tenantId: string;
  readonly replaySequence: number;
  readonly witnessId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly schemaVersion: string;
  readonly timestamp: string;
  readonly contentHash: string;
}

export type ProjectEvent = ProjectCreated | ProjectCompleted;

// ---------------------------------------------------------------------------
// Event Stream Interface
// ---------------------------------------------------------------------------

export interface EventStream {
  readonly aggregateId: string;
  readonly events: readonly ProjectEvent[];
  readonly version: number;
}

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

export class ProjectRepository {
  private readonly authority = "ProjectAuthority";

  /**
   * Load an aggregate by replaying its event stream.
   */
  async load(aggregateId: string): Promise<ProjectState | null> {
    const stream = await this.loadEventStream(aggregateId);
    if (stream.events.length === 0) return null;

    return ProjectAggregate.fromEvents(aggregateId, stream.events);
  }

  /**
   * Save new events for an aggregate.
   * Events are append-only; state is derived at read time.
   */
  async save(state: ProjectState, events: ProjectEvent[]): Promise<void> {
    if (events.length === 0) return;
    await this.appendToStream(state.id, events, state.version);
  }

  /**
   * Apply a single event to the current state.
   * This is the pure function: state + event → new state.
   * Static — callable without an instance (used by replay dispatch).
   */
  static apply(state: ProjectState, event: ProjectEvent): ProjectState {
    switch (event.type) {
      case "ProjectCreated":
        return ProjectRepository.applyProjectCreated(state, event);
      case "ProjectCompleted":
        return ProjectRepository.applyProjectCompleted(state, event);
      default:
        return state;
    }
  }

  // -------------------------------------------------------------------------
  // Event applicators (one per event type)
  // -------------------------------------------------------------------------

  private static applyProjectCreated(state: ProjectState, event: ProjectCreated): ProjectState {
    return {
      ...state,
      version: state.version + 1,
      events: [...state.events, event],
      status: "projectCreated",
    };
  }

  private static applyProjectCompleted(state: ProjectState, event: ProjectCompleted): ProjectState {
    return {
      ...state,
      version: state.version + 1,
      events: [...state.events, event],
      status: "projectCompleted",
    };
  }

  // -------------------------------------------------------------------------
  // Snapshot interface (stub — Sprint 2 future)
  // -------------------------------------------------------------------------

  /**
   * Take a snapshot of the current state.
   * Stub: returns state as-is. Implement snapshot storage in production.
   */
  async snapshot(state: ProjectState): Promise<ProjectState> {
    return state;
  }

  /**
   * Load from snapshot + replay remaining events.
   * Stub: ignores snapshot, loads from event stream.
   */
  async loadFromSnapshot(_snapshotId: string, aggregateId: string): Promise<ProjectState | null> {
    return this.load(aggregateId);
  }

  // -------------------------------------------------------------------------
  // Authority hook interface
  // -------------------------------------------------------------------------

  /**
   * Called before a command is executed.
   * Return true to allow, false to reject.
   * Stub: always allows. Wire to authority policies in production.
   */
  async beforeCommand(_command: string, _aggregateId: string, _tenantId: string): Promise<boolean> {
    return true;
  }

  /**
   * Called after events are persisted.
   * Stub: no-op. Wire to projection/notification in production.
   */
  async afterSave(_state: ProjectState, _events: ProjectEvent[]): Promise<void> {
    // Wire to projections here
  }

  /**
   * Register a projection for this aggregate.
   * Stub: no-op. Wire to projection registry in production.
   */
  async registerProjection(_name: string, _handler: unknown): Promise<void> {
    // Wire to projection registry here
  }

  // -------------------------------------------------------------------------
  // Internal (stub implementations — wire to event store in production)
  // -------------------------------------------------------------------------

  protected async loadEventStream(aggregateId: string): Promise<EventStream> {
    // TODO: Wire to event store
    return { aggregateId, events: [], version: 0 };
  }

  protected async appendToStream(
    _aggregateId: string,
    _events: ProjectEvent[],
    _expectedVersion: number,
  ): Promise<void> {
    // TODO: Wire to event store
  }
}
