/**
 * CrewStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Crew
 */

export type CrewState = "initial" | "active" | "completed";

export interface CrewStateMachine {
  readonly currentState: CrewState;
  readonly transitions: readonly CrewTransition[];
}

export interface CrewTransition {
  readonly from: CrewState;
  readonly to: CrewState;
  readonly event: string;
  readonly guard?: string;
}

export const crewStateMachine: CrewStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isCrewStateMachine(machine: { currentState: string }): machine is CrewStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
