/**
 * CustomerStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Customer
 */

export type CustomerState = "initial" | "active" | "completed";

export interface CustomerStateMachine {
  readonly currentState: CustomerState;
  readonly transitions: readonly CustomerTransition[];
}

export interface CustomerTransition {
  readonly from: CustomerState;
  readonly to: CustomerState;
  readonly event: string;
  readonly guard?: string;
}

export const customerStateMachine: CustomerStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isCustomerStateMachine(machine: { currentState: string }): machine is CustomerStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
