/**
 * EstimateStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Estimate
 */

export type EstimateState = "initial" | "active" | "completed";

export interface EstimateStateMachine {
  readonly currentState: EstimateState;
  readonly transitions: readonly EstimateTransition[];
}

export interface EstimateTransition {
  readonly from: EstimateState;
  readonly to: EstimateState;
  readonly event: string;
  readonly guard?: string;
}

export const estimateStateMachine: EstimateStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isEstimateStateMachine(machine: { currentState: string }): machine is EstimateStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
