/**
 * JobStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Job
 */

export type JobState = "initial" | "active" | "completed";

export interface JobStateMachine {
  readonly currentState: JobState;
  readonly transitions: readonly JobTransition[];
}

export interface JobTransition {
  readonly from: JobState;
  readonly to: JobState;
  readonly event: string;
  readonly guard?: string;
}

export const jobStateMachine: JobStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isJobStateMachine(machine: { currentState: string }): machine is JobStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
