/**
 * PDFStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: PDF
 */

export type PDFState = "initial" | "active" | "completed";

export interface PDFStateMachine {
  readonly currentState: PDFState;
  readonly transitions: readonly PDFTransition[];
}

export interface PDFTransition {
  readonly from: PDFState;
  readonly to: PDFState;
  readonly event: string;
  readonly guard?: string;
}

export const pDFStateMachine: PDFStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isPDFStateMachine(machine: { currentState: string }): machine is PDFStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
