/**
 * PhotoStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Photo
 */

export type PhotoState = "initial" | "active" | "completed";

export interface PhotoStateMachine {
  readonly currentState: PhotoState;
  readonly transitions: readonly PhotoTransition[];
}

export interface PhotoTransition {
  readonly from: PhotoState;
  readonly to: PhotoState;
  readonly event: string;
  readonly guard?: string;
}

export const photoStateMachine: PhotoStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isPhotoStateMachine(machine: { currentState: string }): machine is PhotoStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
