/**
 * ProjectStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Project
 */

export type ProjectState = "initial" | "active" | "completed";

export interface ProjectStateMachine {
  readonly currentState: ProjectState;
  readonly transitions: readonly ProjectTransition[];
}

export interface ProjectTransition {
  readonly from: ProjectState;
  readonly to: ProjectState;
  readonly event: string;
  readonly guard?: string;
}

export const projectStateMachine: ProjectStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isProjectStateMachine(machine: { currentState: string }): machine is ProjectStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
