/**
 * StateMachineIR — canonical state machine intermediate representation.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 */

export interface StateMachineIR {
  readonly aggregate: string;
  readonly states: readonly string[];
  readonly transitions: readonly StateMachineIRTransition[];
}

export interface StateMachineIRTransition {
  readonly from: string;
  readonly to: string;
  readonly event: string;
  readonly guard?: string;
}

export const stateMachineIR: readonly StateMachineIR[] = [
  {
    aggregate: "Customer",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Crew",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Vendor",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Estimate",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Job",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Project",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Photo",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Video",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "Voice",
    states: ["initial","active","completed"],
    transitions: [],
  },
  {
    aggregate: "PDF",
    states: ["initial","active","completed"],
    transitions: [],
  }
];
