/**
 * VendorStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Vendor
 */

export type VendorState = "initial" | "active" | "completed";

export interface VendorStateMachine {
  readonly currentState: VendorState;
  readonly transitions: readonly VendorTransition[];
}

export interface VendorTransition {
  readonly from: VendorState;
  readonly to: VendorState;
  readonly event: string;
  readonly guard?: string;
}

export const vendorStateMachine: VendorStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isVendorStateMachine(machine: { currentState: string }): machine is VendorStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
