/**
 * VideoStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Video
 */

export type VideoState = "initial" | "active" | "completed";

export interface VideoStateMachine {
  readonly currentState: VideoState;
  readonly transitions: readonly VideoTransition[];
}

export interface VideoTransition {
  readonly from: VideoState;
  readonly to: VideoState;
  readonly event: string;
  readonly guard?: string;
}

export const videoStateMachine: VideoStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isVideoStateMachine(machine: { currentState: string }): machine is VideoStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
