/**
 * VoiceStateMachine — canonical state machine definition.
 *
 * DO NOT EDIT. Generated by StateMachineGenerator from Canonical IR.
 * Aggregate: Voice
 */

export type VoiceState = "initial" | "active" | "completed";

export interface VoiceStateMachine {
  readonly currentState: VoiceState;
  readonly transitions: readonly VoiceTransition[];
}

export interface VoiceTransition {
  readonly from: VoiceState;
  readonly to: VoiceState;
  readonly event: string;
  readonly guard?: string;
}

export const voiceStateMachine: VoiceStateMachine = {
  currentState: "initial",
  transitions: [
    { from: "initial", to: "active", event: "Created" },
    { from: "initial", to: "active", event: "Updated" },
    { from: "initial", to: "active", event: "Completed" },
    { from: "initial", to: "active", event: "Cancelled" },
  ],
};

/** Type guard */
export function isVoiceStateMachine(machine: { currentState: string }): machine is VoiceStateMachine {
  return machine.currentState === "initial" || machine.currentState === "active" || machine.currentState === "completed";
}
