import { defineConfig } from "eslint/config";
import tsParser from "@typescript-eslint/parser";
import tsPlugin from "@typescript-eslint/eslint-plugin";

const eslintConfig = defineConfig([
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "package/**",
      "scripts/**/*.{js,cjs,mjs,ts}",
      "!scripts/public-projection-policy.cjs",
      "!scripts/audit-production-media.ts",
      "src/shared/connectors/**",
      "src/shared/explorer/**",
      "src/shared/intelligence/**",
      "src/shared/components/reconstruction/**",
      "src/shared/components/replay/**",
      "src/shared/components/diff/**",
      "src/shared/components/inspector/**",
      "src/shared/components/explorer/**",
      "src/objects/**",
      "src/motion/**",
      "src/scripts/**",
      "src/app/admin/**",
      "src/app/api/admin/**",
      "src/app/api/diagnostics/**",
      "src/app/api/auth/google/**",
      "src/app/api/drive/**/*.{ts,tsx}",
      "!src/app/api/drive/**/route.ts",
      "src/services/**",
      "src/types/**",
      "src/lib/**/*.{ts,tsx,js,cjs,mjs}",
      "!src/lib/text-*.ts",
      "!src/lib/content-contract.ts",
      "!src/lib/editable-*-fields.ts",
      "!src/lib/blog-copy.ts",
      "!src/lib/drive/*.ts",
      "!src/lib/r2-storage.ts",
      "!src/lib/r2-public-origin.ts",
      "!src/lib/media-storage-evidence.ts",
      "!src/lib/media-inventory.ts",
      "!src/lib/homepage-service-media.ts",
      "src/app/api/drive-sync/**",
      "src/app/api/estimate/**",
      "src/app/api/kit/**",
      "src/app/api/reviews/**",
      "src/app/blog/**",
      "src/app/contact/**",
      "src/app/estimate/**",
      "src/app/newsletter/**",
      "src/app/reviews/**/*",
      "src/app/workbench/**/*",
      "src/app/our-work/**/*",
      "src/app/projects/**/*",
      "src/app/services/**/*",
      "!src/app/workbench/**/*/",
      "!src/app/projects/**/*/",
      "!src/app/services/**/*/",
      "src/components/**/*.{ts,tsx,js,cjs,mjs}",
      "!src/components/text-copy.tsx",
      "!src/components/content-copy.tsx",
      "!src/components/workbench/preview-text-bridge.tsx",
      "!src/components/workbench/text-editor.tsx",
      "!src/components/workbench/content-manager.tsx",
      "src/generated/**",
      "src/generators/**",
      "src/automation/**",
      "src/compiler/**",
      "src/config/**",
      "!src/components/loading-ui.tsx",
      "!src/components/workbench/media-thumbnail.tsx",
      "!src/components/workbench/drive-connection-status.tsx",
      "!src/components/workbench/workbench-dialog.tsx",
      "!src/components/workbench/replacement-dialog.tsx",
      "!src/components/workbench/WorkbenchShell.tsx",
      "!src/components/project-photos.tsx",
      "!src/components/project-spotlight.tsx",
      "!src/components/project-lightbox.tsx",
      "!src/components/lenis-provider.tsx",
      "!src/components/reviews-filter-client.tsx",
      "!src/app/**/loading.tsx",
      "!src/app/reviews/page.tsx",
      "!src/app/workbench/media/page.tsx",
      "!src/app/workbench/explorer/drive/page.tsx",
    ],
  },
  {
    files: ["src/components/loading-ui.tsx", "src/components/workbench/media-thumbnail.tsx", "src/components/workbench/drive-connection-status.tsx",
      "src/components/workbench/workbench-dialog.tsx", "src/components/workbench/replacement-dialog.tsx",
      "src/components/workbench/WorkbenchShell.tsx", "src/components/project-photos.tsx", "src/components/project-spotlight.tsx",
      "src/components/project-lightbox.tsx",
      "src/components/lenis-provider.tsx",
      "src/components/reviews-filter-client.tsx", "src/app/**/loading.tsx", "src/app/reviews/page.tsx",
      "src/app/workbench/media/page.tsx", "src/app/workbench/explorer/drive/page.tsx", "src/app/page.tsx"],
    languageOptions: { parser: tsParser },
    rules: { "no-unreachable": "error", "no-dupe-keys": "error", "no-unsafe-finally": "error", "no-constant-condition": "error", "no-fallthrough": "error", "valid-typeof": "error", "eqeqeq": "error" },
  },
  {
    files: ["src/lib/text-*.ts", "src/lib/content-contract.ts", "src/lib/editable-*-fields.ts", "src/lib/blog-copy.ts", "src/lib/homepage-service-media.ts",
      "src/components/text-copy.tsx", "src/components/content-copy.tsx", "src/components/workbench/preview-text-bridge.tsx",
      "src/components/workbench/text-editor.tsx", "src/components/workbench/content-manager.tsx",
      "src/lib/drive/*.ts", "src/lib/r2-*.ts", "src/lib/media-storage-evidence.ts",
      "src/lib/media-inventory.ts", "src/app/api/drive/**/route.ts", "scripts/public-projection-policy.cjs", "scripts/audit-production-media.ts",
      "src/app/api/workbench/media-audit/route.ts", "src/app/api/workbench/auth-status/route.ts"],
    languageOptions: { parser: tsParser },
    plugins: { "@typescript-eslint": tsPlugin },
    // Existing typed API suppressions remain scoped while their rules are introduced progressively.
    linterOptions: { reportUnusedDisableDirectives: false },
    rules: {
      "no-unreachable": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-unsafe-finally": "error",
      "no-constant-condition": "error",
      "no-fallthrough": "error",
      "constructor-super": "error",
      "valid-typeof": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "eqeqeq": "error",
    },
  },
  {
    files: ["src/lib/drive/session-renewal.ts", "src/lib/drive/authenticated-activity.ts",
      "src/lib/drive/reauthorization-identity.ts", "src/lib/media-storage-evidence.ts", "src/lib/media-inventory.ts",
      "scripts/audit-production-media.ts"],
    rules: { "@typescript-eslint/no-explicit-any": "error", "@typescript-eslint/no-unused-vars": "error" },
  },
  {
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
  },
]);

export default eslintConfig;
